/**
 * embed-fonts.mjs
 * Inlines the brand woff2 fonts as base64 data URIs into src/fonts-data.ts so
 * renders never depend on a network fetch. Run after changing public/fonts.
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");

const FACES = [
  ["QUICHE_BOLD", "public/fonts/QuicheSans-Bold.woff2"],
  ["URBANIST_REGULAR", "public/fonts/Urbanist-Regular.woff2"],
  ["URBANIST_BOLD", "public/fonts/Urbanist-Bold.woff2"],
];

const header =
  "/* AUTO-GENERATED by scripts/embed-fonts.mjs. Brand fonts inlined as woff2 data URIs\n" +
  " * so renders never depend on a network fetch (which stalls under concurrency). */\n\n";

const body = FACES.map(([name, rel]) => {
  const b64 = fs.readFileSync(path.join(ROOT, rel)).toString("base64");
  return `export const ${name} = "data:font/woff2;base64,${b64}";`;
}).join("\n");

const out = path.join(ROOT, "src", "fonts-data.ts");
fs.writeFileSync(out, header + body + "\n");
console.log(`Wrote ${path.relative(ROOT, out)} (${fs.statSync(out).size} bytes)`);
