/**
 * prepare.mjs <slug> [--model medium.en]
 *
 * Turns a reel voiceover into perfectly-synced reel data:
 *   1. Convert the voiceover -> 16kHz mono wav (ffmpeg-static)
 *   2. Transcribe with Whisper (word-level timestamps)
 *   3. Write captions.json (drives the TikTok-style captions)
 *   4. Write a PROVISIONAL timeline.json (aligned:false) for preview
 *
 * The authoritative, fixed captions + timeline come from scripts/preflight.py,
 * which runs next: it relabels captions to the ground-truth script, trims phantom
 * audio, restores dropped tails, and recomputes scene cuts (aligned:true). The
 * render is gated on preflight passing.
 *
 * Voiceover source (mp3-first, wav-fallback):
 *   - voiceover.mp3 if present  -> manual ElevenLabs recording (preferred)
 *   - else voiceover.wav        -> generated by scripts/generate_voice.py (OmniVoice)
 *
 * Run AFTER the voiceover exists in the reel folder, then preflight, then render.
 */
import path from "path";
import fs from "fs";
import { fileURLToPath } from "url";
import { execFileSync } from "child_process";
import ffmpegPath from "ffmpeg-static";
import {
  downloadWhisperModel,
  installWhisperCpp,
  transcribe,
  toCaptions,
} from "@remotion/install-whisper-cpp";

const FPS = 30; // must match src/brand.ts VIDEO.fps
const WHISPER_VERSION = "1.5.5";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");

const slug = process.argv[2];
if (!slug) {
  console.error("Usage: node scripts/prepare.mjs <slug> [--model medium.en]");
  process.exit(1);
}
const modelArgIdx = process.argv.indexOf("--model");
const model = modelArgIdx !== -1 ? process.argv[modelArgIdx + 1] : "medium.en";

const reelDir = path.join(ROOT, "public", "reels", slug);
const mp3Path = path.join(reelDir, "voiceover.mp3");
const genWavPath = path.join(reelDir, "voiceover.wav");
const wavPath = path.join(reelDir, "voiceover.16k.wav");
const contentPath = path.join(reelDir, "content.json");
const captionsPath = path.join(reelDir, "captions.json");
const timelinePath = path.join(reelDir, "timeline.json");

// mp3-first (manual ElevenLabs), wav-fallback (OmniVoice generate_voice.py).
const sourcePath = fs.existsSync(mp3Path)
  ? mp3Path
  : fs.existsSync(genWavPath)
    ? genWavPath
    : null;
if (!sourcePath) {
  console.error(
    `Missing voiceover. Either drop an ElevenLabs voiceover.mp3 into ${reelDir},\n` +
    `or generate one: python scripts/generate_voice.py ${slug}`
  );
  process.exit(1);
}
console.log(`→ Using ${path.basename(sourcePath)}`);
if (!fs.existsSync(contentPath)) {
  console.error(`Missing ${contentPath}.`);
  process.exit(1);
}

const norm = (s) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9']/g, " ")
    .replace(/\s+/g, " ")
    .trim();

const main = async () => {
  // 1. source -> 16kHz mono wav (for Whisper)
  console.log("→ Converting audio to 16kHz wav...");
  execFileSync(ffmpegPath, ["-i", sourcePath, "-ar", "16000", "-ac", "1", wavPath, "-y"], {
    stdio: "ignore",
  });

  // The render (src/Root.tsx) plays voiceover.wav when present, so the file we
  // transcribe must equal the file that plays. If the source is the manual mp3,
  // (re)generate voiceover.wav from it so playback stays in sync with captions.
  if (sourcePath === mp3Path) {
    console.log("→ Writing voiceover.wav from mp3 for in-sync playback...");
    execFileSync(ffmpegPath, ["-i", mp3Path, "-ar", "44100", "-ac", "1", genWavPath, "-y"], {
      stdio: "ignore",
    });
  }

  // 2. Whisper
  const whisperDir = path.join(ROOT, "whisper.cpp");
  console.log("→ Ensuring Whisper.cpp + model (first run downloads, can take a few minutes)...");
  await installWhisperCpp({ to: whisperDir, version: WHISPER_VERSION });
  await downloadWhisperModel({ model, folder: whisperDir });

  console.log("→ Transcribing...");
  const whisperCppOutput = await transcribe({
    model,
    whisperPath: whisperDir,
    whisperCppVersion: WHISPER_VERSION,
    inputPath: wavPath,
    tokenLevelTimestamps: true,
  });

  // 3. captions.json
  const { captions } = toCaptions({ whisperCppOutput });
  fs.writeFileSync(captionsPath, JSON.stringify(captions, null, 2));
  console.log(`✓ Wrote ${path.relative(ROOT, captionsPath)} (${captions.length} words)`);

  // 4. Align scenes to spoken audio
  const content = JSON.parse(fs.readFileSync(contentPath, "utf8"));
  const words = captions
    .map((c) => ({ w: norm(c.text), startMs: c.startMs, endMs: c.endMs }))
    .filter((c) => c.w.length > 0);

  const lastEndMs = words.length ? words[words.length - 1].endMs : 0;
  const durationMs = Math.ceil(lastEndMs + 600); // small tail so audio never clips
  const durationInFrames = Math.ceil((durationMs / 1000) * FPS);

  // Anchor each scene (after the first) on the first 2 words of its voiceText.
  let cursor = 0;
  const startMsForScene = content.scenes.map((scene, i) => {
    if (i === 0) return 0;
    const tokens = norm(scene.voiceText).split(" ").filter(Boolean);
    const a = tokens[0];
    const b = tokens[1];
    for (let j = cursor; j < words.length - 1; j++) {
      if (words[j].w === a && (!b || words[j + 1].w === b)) {
        cursor = j;
        return words[j].startMs;
      }
    }
    // Fallback: proportional by cumulative word count if anchor not found.
    const wc = content.scenes.slice(0, i).reduce((s, sc) => s + norm(sc.voiceText).split(" ").filter(Boolean).length, 0);
    const idx = Math.min(words.length - 1, wc);
    return words[idx] ? words[idx].startMs : 0;
  });

  const scenes = content.scenes.map((scene, i) => {
    const startFrame = Math.round((startMsForScene[i] / 1000) * FPS);
    const endFrame =
      i < content.scenes.length - 1
        ? Math.round((startMsForScene[i + 1] / 1000) * FPS)
        : durationInFrames;
    return { sceneId: scene.id, startFrame, endFrame };
  });

  // Provisional only (aligned:false). preflight.py writes the authoritative,
  // ground-truth-corrected captions + timeline (aligned:true) and the render gate.
  const timeline = { fps: FPS, durationInFrames, durationMs, aligned: false, scenes };
  fs.writeFileSync(timelinePath, JSON.stringify(timeline, null, 2));
  console.log(`✓ Wrote ${path.relative(ROOT, timelinePath)} (provisional, ${(durationMs / 1000).toFixed(1)}s, ${scenes.length} scenes)`);

  // Clean up the intermediate wav.
  fs.rmSync(wavPath, { force: true });
  console.log("\nDone. Now run the QA gate, then render:");
  console.log(`  .venv/Scripts/python.exe scripts/preflight.py ${slug} --fix`);
  console.log(`  npx remotion render Reel out/${slug}.mp4 --props='{"slug":"${slug}"}'`);
};

main().catch((err) => {
  console.error("prepare.mjs failed:", err);
  process.exit(1);
});
