#!/usr/bin/env python3
"""BUILD mode: write the artifacts, not another description of them.

AUDIT mode ends at a diagnosis. BUILD mode ends at files someone can deploy - a corrected
robots.txt, the URL list a clean sitemap should contain, a flattened redirect map, the two
JSON-LD blocks worth having, and either a corrected hreflang set or a written record that it
does not apply.

Two rules this module holds to, both of which are easy to break and embarrassing when broken:

  1. **Never emit an artifact that fails this skill's own checks.** A generated robots.txt
     that omits the sitemap directive, or a generated sitemap containing a 404, would be an
     audit shipping the defect it just charged to find. Every artifact here is built from
     the same rules technical.py enforces, and `--verify` re-runs those rules against what
     was written.

  2. **Never invent a fact.** `sameAs` needs the client's real profile URLs and there is no
     way to know them from a crawl, so they are emitted as marked placeholders that fail
     loudly rather than plausible guesses that ship silently. Same for the Organization
     legal name. A placeholder someone must fill is honest; a fabricated LinkedIn URL in a
     client's structured data is not.

Nothing here is written to the live site. These are files in an output directory plus a
README explaining what each one is and where it goes.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from urllib.parse import urlparse

sys.path.insert(0, str(Path(__file__).resolve().parent))

import crawl  # noqa: E402
from technical import _has_noindex, _live  # noqa: E402

PLACEHOLDER = "<<FILL IN>>"

# course/21's 2026 default: block the training crawlers, allow the retrieval crawlers that
# send referrals. `anthropic-ai` is deprecated and deliberately absent.
AI_POLICY = """# AI crawler policy. Training crawlers blocked, retrieval crawlers allowed -
# they send referral traffic. Review this as a business decision, not a default.
User-agent: GPTBot
Disallow: /

User-agent: ClaudeBot
Disallow: /

User-agent: CCBot
Disallow: /

User-agent: Google-Extended
Disallow: /

User-agent: OAI-SearchBot
Allow: /

User-agent: ChatGPT-User
Allow: /

User-agent: Claude-SearchBot
Allow: /

User-agent: PerplexityBot
Allow: /
"""


# --------------------------------------------------------------------------- robots.txt

def build_robots(g: dict) -> tuple[str, list[str]]:
    """A corrected robots.txt plus the list of changes made, so nothing lands unexplained."""
    rb = g.get("robots") or {}
    origin = (g.get("origin") or "").rstrip("/")
    changes: list[str] = []

    keep = [d for d in (rb.get("disallows") or [])
            if d and d != "/" and not re.search(
                r"\.(css|js)|/wp-includes|/wp-content/themes|/assets|/static", d, re.I)]
    dropped = [d for d in (rb.get("disallows") or []) if d not in keep]
    if "/" in dropped:
        changes.append("Removed `Disallow: /` - it was blocking the entire site (course/21).")
    for d in dropped:
        if d != "/":
            changes.append(f"Removed `Disallow: {d}` - it blocks CSS or JS, so Google evaluates "
                           "a broken render of the page (course/21).")

    sitemaps = list(rb.get("sitemaps") or [])
    if not sitemaps:
        sitemaps = [f"{origin}/sitemap.xml"]
        changes.append("Added the Sitemap: directive, which was missing (course/21).")

    declared = rb.get("ai_policy_declared") or {}
    if not declared:
        changes.append("Added an explicit AI crawler policy. Previously undeclared, which is a "
                       "default rather than a decision (course/21 -> course/40).")
    if rb.get("mentions_deprecated_anthropic_ai"):
        changes.append("Dropped the deprecated `anthropic-ai` agent. The live agents are "
                       "ClaudeBot (training) and Claude-SearchBot (retrieval).")

    lines = ["# robots.txt - generated by seo-technical. Review before deploying.",
             "# Must return HTTP 200. A 5xx here stops Googlebot crawling the whole site.",
             "", "User-agent: *", "Allow: /"]
    lines += [f"Disallow: {d}" for d in keep]
    lines += ["", AI_POLICY.rstrip(), ""]
    lines += [f"Sitemap: {s}" for s in sitemaps]
    lines.append("")

    if g.get("skipped_by_robots"):
        changes.append(
            f"NOTE: {len(g['skipped_by_robots'])} URL(s) were disallowed at crawl time. If any "
            "of them also carry `noindex`, that combination is broken - a disallowed URL is "
            "never fetched, so the noindex is never read, and the URL can stay indexed as a "
            "bare link forever. Pick one: allow crawling and keep noindex, or disallow and "
            "accept the bare URL (course/21).")
    return "\n".join(lines), changes


# --------------------------------------------------------------------------- sitemap

def build_sitemap(g: dict) -> tuple[str, list[str], list[str]]:
    """(xml, included, excluded-with-reason). Only what course/22 permits."""
    # Every crawled URL, not just the healthy ones. _live() drops non-200s, and filtering
    # first would silently swallow the 404s and redirects this file exists to explain the
    # exclusion of - the excluded list is half the deliverable.
    pages = g.get("pages") or {}
    disallowed = set(g.get("sitemap_urls_disallowed") or [])
    included, excluded = [], []

    for u, p in sorted(pages.items()):
        why = None
        ctype = p.get("content_type") or ""
        if ctype and not ctype.startswith("text/html"):
            why = f"not HTML ({ctype})"
        elif p.get("status") != 200:
            why = f"HTTP {p['status']}"
        elif p.get("redirect_chain"):
            why = f"redirects to {p.get('final_url')}"
        elif _has_noindex(p):
            why = "noindex"
        elif p.get("canonical") and crawl.normalize_url(p["canonical"]) != crawl.normalize_url(u):
            why = f"canonicalized to {p['canonical']}"
        elif u in disallowed:
            why = "disallowed in robots.txt"
        (excluded.append(f"{u} - {why}") if why else included.append(u))

    # A capped crawl means this file is a SUBSET, and deploying a subset silently drops every
    # URL the crawl never reached. On the first live run that was 25 of 38 submitted URLs -
    # a generated artifact that would have removed 13 pages from the client's sitemap.
    stats = g.get("stats") or {}
    submitted = len(g.get("sitemap_urls_submitted") or [])
    warning = ""
    if stats.get("hit_cap") or submitted > len(included) + len(excluded):
        warning = (
            f'\n<!-- INCOMPLETE - DO NOT DEPLOY AS-IS.\n'
            f'     The crawl stopped at its {stats.get("cap")}-page cap, so this file covers\n'
            f'     only the {len(included)} URL(s) it verified. The site submits {submitted}.\n'
            f'     Deploying this would remove every unverified URL from the sitemap.\n'
            f'     Re-run: crawl.py <url> --max-pages {max(submitted * 2, 300)} --yes --refresh\n'
            f'     then emit.py again. -->\n')

    body = "\n".join(f"  <url>\n    <loc>{u}</loc>\n  </url>" for u in included)
    xml = ('<?xml version="1.0" encoding="UTF-8"?>\n'
           '<!-- Generated by seo-technical. Only 200-status, canonical, indexable URLs.\n'
           '     Add a real <lastmod> per URL from your CMS: Google uses it as a recrawl\n'
           '     hint, and one date across every URL is a recognised bad pattern that\n'
           '     destroys its value. priority and changefreq are ignored - do not add them. -->'
           f'{warning}\n'
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
           f"{body}\n</urlset>\n")
    return xml, included, excluded


# --------------------------------------------------------------------------- redirects

def build_redirects(g: dict) -> tuple[str, list[str]]:
    """A flattened one-hop map: every source pointed straight at its final destination."""
    pages = g.get("pages") or {}
    rows = ["from,to,was,note"]
    notes: list[str] = []

    for u, p in sorted(pages.items()):
        hops = p.get("redirect_chain") or []
        if not hops:
            continue
        final = p.get("final_url") or u
        codes = "->".join(str(h["status"]) for h in hops)
        note = []
        if len(hops) > 1:
            note.append(f"flattened {len(hops)} hops to 1")
        if any(h["status"] in (302, 303, 307) for h in hops):
            note.append("was temporary, now 301")
        rows.append(f"{u},{final},{codes},{'; '.join(note) or 'unchanged'}")

    stale = []
    redirecting = {u for u, p in pages.items() if p.get("redirect_chain")}
    for u, p in pages.items():
        for tgt in p.get("internal_outlinks") or []:
            if crawl.normalize_url(tgt) in redirecting:
                stale.append(f"{u} -> {tgt}")
    if stale:
        notes.append(f"{len(stale)} internal link(s) point at a redirect. Repoint them at the "
                     "final destination - a redirect should be a fallback for external links, "
                     "not a routine internal hop (course/24).")
    if len(rows) == 1:
        notes.append("No redirects found in the crawl, so this map is empty. That is the "
                     "desired state.")
    return "\n".join(rows) + "\n", notes


# --------------------------------------------------------------------------- schema

def build_schema(g: dict) -> tuple[str, str, list[str]]:
    """Organization and BreadcrumbList: the highest-value, lowest-effort pair (course/30)."""
    origin = (g.get("origin") or "").rstrip("/")
    pages = _live(g.get("pages") or {})
    # Both spellings: normalize_url keeps "/" and "" distinct on purpose (course/23), so a
    # crawl seeded without a trailing slash keys the homepage without one.
    home = pages.get(crawl.normalize_url(origin + "/")) or \
        pages.get(crawl.normalize_url(origin)) or {}
    # The organization name is a PLACEHOLDER, never derived from the homepage title.
    # Splitting "Festival | Example Faire | Example City" on the first pipe yields
    # "Festival", which would ship as a client's legal entity name in their structured data.
    # The title is offered in the notes as a hint for a human to read, which is a different
    # thing from a guess.
    title_hint = (home.get("title") or "").strip()

    org = {
        "@context": "https://schema.org",
        "@type": "Organization",
        "@id": f"{origin}/#organization",
        "name": PLACEHOLDER,
        "url": origin + "/",
        "logo": f"{origin}/{PLACEHOLDER}",
        "sameAs": [f"https://www.linkedin.com/company/{PLACEHOLDER}",
                   f"https://www.facebook.com/{PLACEHOLDER}"],
    }

    # A worked example from a real deep URL, so the developer sees the shape against their
    # own paths rather than against example.com.
    deep = next((u for u, p in sorted(pages.items()) if (p.get("depth") or 0) >= 2), None)
    segs = [s for s in urlparse(deep or origin + "/a/b").path.split("/") if s]
    items, acc = [], origin
    for i, seg in enumerate(["Home"] + segs, start=1):
        acc = origin + "/" if i == 1 else acc.rstrip("/") + "/" + segs[i - 2]
        items.append({"@type": "ListItem", "position": i,
                      "name": "Home" if i == 1 else seg.replace("-", " ").title(),
                      "item": acc})
    crumbs = {"@context": "https://schema.org", "@type": "BreadcrumbList",
              "@id": f"{deep or origin}/#breadcrumb", "itemListElement": items}

    notes = [
        f"Organization name is a placeholder on purpose. The homepage title is "
        f"{title_hint!r} - read the real legal or trading name off that, do not let a script "
        "split it on a pipe and guess." if title_hint else
        "Organization name is a placeholder: the homepage was not in the crawl.",
        f"Both blocks go in the <head> as <script type=\"application/ld+json\">. Every "
        f"{PLACEHOLDER} must be replaced with a real value - they are placeholders precisely "
        "so they fail loudly instead of shipping a fabricated profile URL in the client's "
        "structured data.",
        "sameAs is the entity anchor: point it at the real LinkedIn, Crunchbase and social "
        "profiles. This is what course/40's entity work builds on.",
        "BreadcrumbList is a template, not a page. Generate it from the page's real position "
        "in the hierarchy - the example below is built from an actual URL on this site.",
        "Schema is not a ranking factor and the two causal studies of schema against AI "
        "citations found no uplift. Implement it for rich-result eligibility and entity "
        "clarity, and say that to the client rather than promising rankings.",
    ]
    return (json.dumps(org, indent=2), json.dumps(crumbs, indent=2), notes)


# --------------------------------------------------------------------------- hreflang

def build_hreflang(g: dict) -> str:
    pages = _live(g.get("pages") or {})
    tagged = {u: p["hreflang"] for u, p in pages.items() if p.get("hreflang")}
    if not tagged:
        return (
            "# hreflang: not applicable\n\n"
            f"No hreflang was found on any of the {len(pages)} crawled pages, and nothing in "
            "the crawl suggests multiple language or region versions.\n\n"
            "This is a legitimate audit outcome, recorded deliberately rather than left "
            "blank, so nobody implements hreflang later for no reason. Most sites do not need "
            "it: one well-executed site usually outperforms three thin translated ones, and "
            "every hreflang failure mode is silent.\n\n"
            "It becomes applicable only with substantially the same content in multiple "
            "languages, or targeted at multiple countries with real differences - currency, "
            "pricing, shipping, legal terms. Not a currency symbol swap.\n\n"
            "If that changes: use subdirectories (`/de/`) unless the market genuinely demands "
            "a local domain, declare every version on every page including itself, always "
            "include x-default, and verify the return links by hand on three pages.\n")

    lines = ["# hreflang set", "",
             "Every page below must carry its whole set, including a self-reference and "
             "x-default. hreflang is bidirectional: if A declares B, B must declare A, and a "
             "one-way declaration is ignored entirely.", ""]
    for u, alts in sorted(tagged.items()):
        lines.append(f"## {u}")
        lines.append("```html")
        seen = {a.get("lang", "").lower() for a in alts}
        for a in alts:
            lines.append(f'<link rel="alternate" hreflang="{a.get("lang")}" '
                         f'href="{a.get("href")}" />')
        if not any(crawl.normalize_url(a.get("href", "")) == crawl.normalize_url(u) for a in alts):
            lines.append(f'<link rel="alternate" hreflang="{PLACEHOLDER}" href="{u}" />  '
                         '<!-- ADDED: the page was missing its own self-reference -->')
        if "x-default" not in seen:
            lines.append(f'<link rel="alternate" hreflang="x-default" href="{u}" />  '
                         '<!-- ADDED: x-default was missing -->')
        lines += ["```", ""]
    return "\n".join(lines)


# --------------------------------------------------------------------------- write

def emit(g: dict, outdir: Path) -> dict:
    outdir.mkdir(parents=True, exist_ok=True)
    written = {}

    robots, robots_changes = build_robots(g)
    (outdir / "robots.txt").write_text(robots, encoding="utf-8")
    written["robots.txt"] = robots_changes

    xml, included, excluded = build_sitemap(g)
    (outdir / "sitemap.xml").write_text(xml, encoding="utf-8")
    (outdir / "sitemap-excluded.txt").write_text(
        "\n".join(excluded) + "\n" if excluded else "none\n", encoding="utf-8")
    written["sitemap.xml"] = [f"{len(included)} URL(s) included, {len(excluded)} excluded "
                              "(reasons in sitemap-excluded.txt)"]

    csv, redirect_notes = build_redirects(g)
    (outdir / "redirects.csv").write_text(csv, encoding="utf-8")
    written["redirects.csv"] = redirect_notes

    org, crumbs, schema_notes = build_schema(g)
    (outdir / "organization.jsonld").write_text(org, encoding="utf-8")
    (outdir / "breadcrumbs.jsonld").write_text(crumbs, encoding="utf-8")
    written["organization.jsonld / breadcrumbs.jsonld"] = schema_notes

    (outdir / "hreflang.md").write_text(build_hreflang(g), encoding="utf-8")
    written["hreflang.md"] = ["Either the corrected set or a documented not-applicable."]

    readme = [f"# Technical SEO artifacts - {g.get('origin')}", "",
              f"Generated from a crawl of {(g.get('stats') or {}).get('pages_crawled')} pages "
              f"on {g.get('crawled_at')}.", "",
              "Nothing here has been deployed. Review each file, then ship it.", ""]
    for fname, notes in written.items():
        readme += [f"## {fname}", ""]
        readme += [f"- {n}" for n in notes] or ["- No changes needed."]
        readme.append("")
    readme += ["## Order", "",
               "Deploy in tier order (course/21). robots.txt and the sitemap first, because a "
               "page that is not crawled or indexed cannot rank and nothing above that layer "
               "changes it. Redirects next. Schema last - it is the polish, and polishing an "
               "unindexed page is polishing something invisible.", "",
               "After deploying: confirm robots.txt returns 200, resubmit the sitemap in "
               "Search Console, and re-run `crawl.py <url> --refresh` followed by "
               "`technical.py <url>` to verify the findings closed."]
    (outdir / "README.md").write_text("\n".join(readme), encoding="utf-8")
    return written


def verify(outdir: Path) -> list[str]:
    """Re-run this skill's own rules against what was just written. Empty means clean."""
    problems = []
    robots = (outdir / "robots.txt")
    if robots.exists():
        text = robots.read_text(encoding="utf-8")
        groups = crawl._robots_groups(text)
        star = crawl._rules_for(groups, "*")
        if ("disallow", "/") in star:
            problems.append("robots.txt: the generated file blocks the whole site for *.")
        if not any(k == "sitemap" for _, rules in groups for k, _ in rules):
            problems.append("robots.txt: no Sitemap: directive in the generated file.")
        if any(a.lower() == "anthropic-ai" for agents, _ in groups for a in agents):
            problems.append("robots.txt: the deprecated anthropic-ai agent was emitted.")
        if any(re.search(r"\.(css|js)|/assets|/static", v, re.I)
               for k, v in star if k == "disallow"):
            problems.append("robots.txt: the generated file blocks CSS or JS.")

    sm = (outdir / "sitemap.xml")
    if sm.exists():
        text = sm.read_text(encoding="utf-8")
        if "<priority>" in text or "<changefreq>" in text:
            problems.append("sitemap.xml: priority/changefreq emitted, and Google ignores both.")
        if "<loc>" not in text:
            problems.append("sitemap.xml: no URLs. Nothing on the site qualified, which is "
                            "itself the finding - do not ship an empty sitemap.")
        if "INCOMPLETE - DO NOT DEPLOY" in text:
            problems.append(
                "sitemap.xml: generated from a capped crawl, so it is a subset of the site. "
                "Deploying it would drop every URL the crawl never reached. Re-crawl with a "
                "higher --max-pages and regenerate. (Header comment has the exact command.)")

    for f in ("organization.jsonld", "breadcrumbs.jsonld"):
        p = outdir / f
        if p.exists():
            try:
                json.loads(p.read_text(encoding="utf-8"))
            except json.JSONDecodeError as exc:
                problems.append(f"{f}: not valid JSON ({exc}).")
    return problems


# --------------------------------------------------------------------------- selftest

def _selftest() -> int:
    import tempfile
    ok = True
    o = "https://e.test"
    g = {
        "origin": o, "crawled_at": "2026-01-01", "stats": {"pages_crawled": 4},
        "robots": {"disallows": ["/", "/assets/app.css", "/private"], "sitemaps": [],
                   "ai_policy_declared": {}, "mentions_deprecated_anthropic_ai": True,
                   "returns_200": True},
        "skipped_by_robots": [f"{o}/secret"],
        "sitemap_urls_disallowed": [],
        "pages": {
            f"{o}/": {"url": f"{o}/", "status": 200, "content_type": "text/html", "depth": 0,
                      "title": "Acme Ltd | Home", "canonical": f"{o}/", "redirect_chain": [],
                      "internal_outlinks": [f"{o}/old"], "hreflang": [], "final_url": f"{o}/"},
            f"{o}/a/b": {"url": f"{o}/a/b", "status": 200, "content_type": "text/html",
                         "depth": 2, "canonical": f"{o}/a/b", "redirect_chain": [],
                         "internal_outlinks": [], "hreflang": [], "final_url": f"{o}/a/b"},
            f"{o}/gone": {"url": f"{o}/gone", "status": 404, "content_type": "text/html",
                          "redirect_chain": [], "internal_outlinks": [], "hreflang": []},
            f"{o}/old": {"url": f"{o}/old", "status": 200, "content_type": "text/html",
                         "final_url": f"{o}/a/b", "canonical": f"{o}/a/b",
                         "redirect_chain": [{"status": 302, "url": f"{o}/old"},
                                            {"status": 301, "url": f"{o}/mid"}],
                         "internal_outlinks": [], "hreflang": []},
        },
    }

    with tempfile.TemporaryDirectory() as td:
        out = Path(td)
        written = emit(g, out)

        print("1. the generated robots.txt fixes what the crawl found broken")
        text = (out / "robots.txt").read_text(encoding="utf-8")
        # Asked of the parsed wildcard group, not of the raw text: the AI policy block
        # legitimately contains `Disallow: /` for GPTBot and ClaudeBot, so a substring
        # search here would fail on a correct file - the same per-agent-versus-site-wide
        # confusion that crawl.py's grouping fix exists to prevent.
        star_rules = crawl._rules_for(crawl._robots_groups(text), "*")
        cases = {
            "Disallow: / removed for *": ("disallow", "/") not in star_rules,
            "AI trainers still blocked": ("disallow", "/") in
                                         crawl._rules_for(crawl._robots_groups(text), "GPTBot"),
            "CSS unblocked": "app.css" not in text,
            "real Disallow kept": "Disallow: /private" in text,
            "sitemap added": "Sitemap: https://e.test/sitemap.xml" in text,
            "AI policy added": "GPTBot" in text and "Claude-SearchBot" in text,
            "deprecated agent gone": "anthropic-ai" not in text,
        }
        bad = [k for k, v in cases.items() if not v]
        print("   PASS: all six corrections applied" if not bad else f"   FAIL: {bad}")
        ok &= not bad

        print("2. every change is explained, not silently applied")
        notes = " ".join(written["robots.txt"])
        if "blocking the entire site" in notes and "blocks CSS or JS" in notes and \
                "never fetched, so the noindex is never read" in notes:
            print("   PASS: each edit carries its reason, plus the disallow+noindex warning")
        else:
            print(f"   FAIL: {written['robots.txt']}")
            ok = False

        print("3. the sitemap contains only what course/22 permits")
        xml = (out / "sitemap.xml").read_text(encoding="utf-8")
        exc = (out / "sitemap-excluded.txt").read_text(encoding="utf-8")
        cases = {
            "200 pages in": f"<loc>{o}/</loc>" in xml and f"<loc>{o}/a/b</loc>" in xml,
            "404 out": f"<loc>{o}/gone</loc>" not in xml,
            "redirect out": f"<loc>{o}/old</loc>" not in xml,
            "reasons recorded": "HTTP 404" in exc and "redirects to" in exc,
            "no priority/changefreq": "<priority>" not in xml,
        }
        bad = [k for k, v in cases.items() if not v]
        print("   PASS: 2 in, 2 excluded with reasons" if not bad else f"   FAIL: {bad}")
        ok &= not bad

        print("4. the redirect map is flattened to one hop and flags stale internal links")
        csv = (out / "redirects.csv").read_text(encoding="utf-8")
        if f"{o}/old,{o}/a/b,302->301,flattened 2 hops to 1; was temporary, now 301" in csv and \
                "internal link(s) point at a redirect" in " ".join(written["redirects.csv"]):
            print("   PASS: chain flattened, 302 corrected, stale internal link named")
        else:
            print(f"   FAIL: {csv!r}")
            ok = False

        print("5. schema uses real site structure but never invents an identity")
        org = json.loads((out / "organization.jsonld").read_text(encoding="utf-8"))
        crumbs = json.loads((out / "breadcrumbs.jsonld").read_text(encoding="utf-8"))
        notes = " ".join(written["organization.jsonld / breadcrumbs.jsonld"])
        if org["name"] == PLACEHOLDER and org["@id"] == f"{o}/#organization" and \
                all(PLACEHOLDER in s for s in org["sameAs"]) and \
                "Acme Ltd | Home" in notes and \
                [i["name"] for i in crumbs["itemListElement"]] == ["Home", "A", "B"]:
            print("   PASS: name and sameAs are loud placeholders, the real title is offered "
                  "as a hint, breadcrumb built from a real URL")
        else:
            print(f"   FAIL: {org} / {notes[:120]}")
            ok = False

        print("5b. splitting a title on a pipe never becomes the organization name")
        # "Festival | Example Faire | Example City" -> "Festival" is the failure this guards.
        g2 = json.loads(json.dumps(g))
        g2["pages"][f"{o}/"]["title"] = "Festival | Example Faire | Example City"
        org2 = json.loads(build_schema(g2)[0])
        if org2["name"] == PLACEHOLDER:
            print("   PASS: a pipe-delimited title yields a placeholder, not 'Festival'")
        else:
            print(f"   FAIL: name became {org2['name']!r}")
            ok = False

        print("6. no hreflang means a written decision, not a blank file")
        h = (out / "hreflang.md").read_text(encoding="utf-8")
        if "not applicable" in h and "so nobody implements hreflang later" in h:
            print("   PASS: the not-applicable case is recorded as a finding")
        else:
            print("   FAIL: hreflang.md did not document the decision")
            ok = False

        print("7. --verify re-runs the skill's own rules against the output")
        problems = verify(out)
        print("   PASS: generated artifacts pass the checks that produced them"
              if not problems else f"   FAIL: {problems}")
        ok &= not problems

        print("7b. a capped crawl marks the sitemap incomplete and fails verify")
        capped = json.loads(json.dumps(g))
        capped["stats"] = {"pages_crawled": 4, "cap": 4, "hit_cap": True}
        capped["sitemap_urls_submitted"] = [f"{o}/x{i}" for i in range(38)]
        xml_capped, _, _ = build_sitemap(capped)
        (out / "sitemap.xml").write_text(xml_capped, encoding="utf-8")
        problems = verify(out)
        if "INCOMPLETE - DO NOT DEPLOY" in xml_capped and "The site submits 38" in xml_capped \
                and any("subset of the site" in p for p in problems):
            print("   PASS: a 4-of-38 sitemap is refused instead of silently dropping 34 URLs")
        else:
            print(f"   FAIL: {problems}")
            ok = False

        print("8. a deliberately broken artifact is caught by --verify")
        (out / "robots.txt").write_text("User-agent: *\nDisallow: /\n", encoding="utf-8")
        problems = verify(out)
        if any("blocks the whole site" in p for p in problems) and \
                any("no Sitemap:" in p for p in problems):
            print("   PASS: verify is a real check, not a rubber stamp")
        else:
            print(f"   FAIL: {problems}")
            ok = False

    print("\nRESULT:", "PASS" if ok else "FAIL")
    return 0 if ok else 1


# --------------------------------------------------------------------------- cli

def main() -> int:
    ap = argparse.ArgumentParser(description="BUILD mode: generate deployable technical artifacts.")
    ap.add_argument("url", nargs="?")
    ap.add_argument("--graph")
    ap.add_argument("--out", default="seo-technical-build", help="output directory")
    ap.add_argument("--max-pages", type=int, default=crawl.DEFAULT_MAX_PAGES)
    ap.add_argument("--refresh", action="store_true")
    ap.add_argument("--yes", action="store_true")
    ap.add_argument("--verify", action="store_true",
                    help="only re-check an existing output directory")
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args()

    if args.selftest:
        return _selftest()
    if args.verify:
        problems = verify(Path(args.out))
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        print("clean" if not problems else f"{len(problems)} problem(s)", file=sys.stderr)
        return 1 if problems else 0
    if not args.graph and not args.url:
        ap.error("url or --graph required (or use --selftest / --verify)")

    if args.graph:
        g = json.loads(Path(args.graph).read_text(encoding="utf-8"))
    else:
        cached = crawl._cache_path(crawl.origin_of(args.url)).exists() and not args.refresh
        if args.max_pages > crawl.CONFIRM_ABOVE and not args.yes and not cached:
            print(f"This would make up to {args.max_pages} requests. Re-run with --yes.",
                  file=sys.stderr)
            return 2
        g = crawl.crawl(args.url, max_pages=args.max_pages, refresh=args.refresh)

    outdir = Path(args.out)
    written = emit(g, outdir)
    problems = verify(outdir)

    print(f"\nWrote {len(list(outdir.iterdir()))} file(s) to {outdir}/\n")
    for fname, notes in written.items():
        print(f"  {fname}")
        for n in notes:
            print(f"    - {n}")
    if problems:
        print("\nVERIFY FAILED - the generated artifacts break this skill's own rules:")
        for p in problems:
            print(f"  - {p}")
        return 1
    print("\nVerified: every generated artifact passes the checks that produced it.")
    print("Nothing was deployed. Read README.md for the deploy order.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
