#!/usr/bin/env python3
"""
Catalog builder for api-scout.
Fetches the public-apis README (github.com/public-apis/public-apis), parses its per-category
markdown tables, and writes catalog/apis.md in api-scout's scannable entry format.

Usage:
    python .claude/skills/api-scout/scripts/fetch_apis.py
    python .claude/skills/api-scout/scripts/fetch_apis.py --output /path/to/catalog.md
    python .claude/skills/api-scout/scripts/fetch_apis.py --source /path/to/local/README.md
"""
from __future__ import annotations

import argparse
import re
import sys
import urllib.request
from datetime import date
from pathlib import Path

README_URL = "https://raw.githubusercontent.com/public-apis/public-apis/master/README.md"

# Matches a table row like: | [Name](url) | Description | `apiKey` | Yes | Yes |
ROW_RE = re.compile(r"^\|\s*\[([^\]]+)\]\(([^)]+)\)\s*\|(.*)$")
CATEGORY_RE = re.compile(r"^### (.+)$")


def fetch_readme(source: str | None) -> str:
    if source:
        return Path(source).read_text(encoding="utf-8")
    with urllib.request.urlopen(README_URL, timeout=30) as resp:
        return resp.read().decode("utf-8")


def parse_row(line: str) -> dict | None:
    m = ROW_RE.match(line.strip())
    if not m:
        return None
    name, url, rest = m.group(1).strip(), m.group(2).strip(), m.group(3)
    cells = [c.strip().strip("`") for c in rest.split("|")]
    cells = [c for c in cells if c]  # drop empty cells from trailing "| |" artifacts
    if not cells:
        return None
    description = cells[0] if len(cells) > 0 else ""
    auth = cells[1] if len(cells) > 1 else "Unknown"
    https = cells[2] if len(cells) > 2 else "Unknown"
    cors = cells[3] if len(cells) > 3 else "Unknown"
    return {
        "name": name,
        "url": url,
        "description": description,
        "auth": auth if auth else "No",
        "https": https,
        "cors": cors,
    }


def parse_catalog(readme: str) -> dict[str, list[dict]]:
    """Parse category sections (### Heading + API table) after the Index.

    Skips the sponsored "APILayer APIs" table at the top of the file — it uses a
    different column layout (no Auth/HTTPS/CORS) and isn't part of the curated
    category list.
    """
    catalog: dict[str, list[dict]] = {}
    current_category: str | None = None
    seen_index = False
    for line in readme.splitlines():
        if line.strip() == "## Index":
            seen_index = True
            continue
        if not seen_index:
            continue
        cat_match = CATEGORY_RE.match(line.strip())
        if cat_match:
            current_category = cat_match.group(1).strip()
            catalog.setdefault(current_category, [])
            continue
        if current_category is None:
            continue
        row = parse_row(line)
        if row:
            catalog[current_category].append(row)
    # Drop categories that ended up empty (e.g. a stray ### heading with no table)
    return {k: v for k, v in catalog.items() if v}


def format_catalog(catalog: dict[str, list[dict]]) -> str:
    total = sum(len(v) for v in catalog.values())
    lines = [
        "# Free & Public API Catalog",
        f"*Last updated: {date.today().isoformat()} — {total} APIs across {len(catalog)} categories*",
        "*Auto-generated by api-scout from github.com/public-apis/public-apis*",
        "",
    ]
    for category, apis in catalog.items():
        lines += [f"## {category}", ""]
        for a in apis:
            lines.append(f"### {a['name']}")
            lines.append(f"- **URL:** {a['url']}")
            lines.append(f"- **Category:** {category}")
            lines.append(f"- **Auth:** {a['auth']}")
            lines.append(f"- **HTTPS:** {a['https']}")
            lines.append(f"- **CORS:** {a['cors']}")
            if a["description"]:
                lines.append(f"- **About:** {a['description']}")
            lines.append("")
    return "\n".join(lines)


def main() -> None:
    p = argparse.ArgumentParser(description="Build the api-scout catalog from public-apis/public-apis.")
    p.add_argument("--output", default=None, help="Output path for catalog.md")
    p.add_argument("--source", default=None, help="Local README.md path instead of fetching from GitHub")
    args = p.parse_args()

    skill_dir = Path(__file__).resolve().parent.parent
    out_path = Path(args.output) if args.output else skill_dir / "catalog" / "apis.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    print("Fetching public-apis README..." if not args.source else f"Reading {args.source}...", flush=True)
    readme = fetch_readme(args.source)

    catalog = parse_catalog(readme)
    if not catalog:
        print("Warning: no categories parsed — check the README format hasn't changed.", file=sys.stderr)
        sys.exit(1)

    out_path.write_text(format_catalog(catalog), encoding="utf-8")
    total = sum(len(v) for v in catalog.values())
    print(f"Done — {total} APIs across {len(catalog)} categories written to {out_path}")


if __name__ == "__main__":
    main()
