'use client';
import { useCallback,useEffect,useRef,useState } from 'react';
import type { SchoolRole,SchoolState,Student,CampusVisit } from '@/lib/school-types';
import { attendanceSummary,feeMoney } from '@/lib/school-types';
import { dateLabel,dayAfter,localDate,timeLabel } from '@/lib/healthcare-types';
import ChatWindow,{visitorId} from './ChatWindow';
import { SIcon,SchoolArt,SModal,SchoolFormModal,type SchoolForm } from './SchoolUI';
import { AttendancePanel,HomeworkPanel,ResultsPanel,TimetablePanel,SchoolEmpty,SBadge,type SchoolView } from './SchoolAcademics';
import { FeesPanel,AdmissionsPanel,CampusBooking,LeavePanel,SchoolInbox } from './SchoolOffice';
import './school.css';
const menus:Record<SchoolRole,[string,string,string,string][]>={
 parent:[['overview','Overview','خلاصہ','grid'],['attendance','Attendance','حاضری','check'],['homework','Homework','ہوم ورک','book'],['results','Results & reports','نتائج اور رپورٹس','cap'],['fees','Fees & receipts','فیس اور رسیدیں','fee'],['timetable','Timetable','شیڈول','calendar'],['admissions','Admissions & visits','داخلہ اور ملاقاتیں','users'],['leave','Leave requests','چھٹی کی درخواستیں','leave'],['messages','Messages','پیغامات','chat']],
 school:[['overview','Overview','خلاصہ','grid'],['students','Students','طلبہ','users'],['attendance','Attendance','حاضری','check'],['fees','Fees & payments','فیس اور ادائیگی','fee'],['admissions','Admissions & visits','داخلہ اور ملاقاتیں','cap'],['calendar','Office calendar','دفتر کیلنڈر','calendar'],['leave','Leave requests','چھٹی کی درخواستیں','leave'],['timetable','Timetable','شیڈول','clock'],['notices','Announcements','اعلانات','notice'],['inbox','Conversation inbox','گفتگو ان باکس','chat']],
 teacher:[['overview','Overview','خلاصہ','grid'],['students','My students','میرے طلبہ','users'],['attendance','Attendance','حاضری','check'],['homework','Homework & responses','ہوم ورک اور جوابات','book'],['results','Assessments & reports','امتحانات اور رپورٹس','cap'],['timetable','My timetable','میرا شیڈول','calendar'],['leave','Student leave','طلبہ کی چھٹی','leave']]
};
export default function School({slug,token,name,role,initialLang,initialTab,initialVisit=false,initialEnquiry=false,initialProgram}:{slug:string;token:string;name:string;role:SchoolRole;initialLang:'en'|'ur';initialTab?:string;initialVisit?:boolean;initialEnquiry?:boolean;initialProgram?:string}){
 const [lang,setLang]=useState(initialLang),ur=lang==='ur',t=useCallback((en:string,urdu:string)=>lang==='ur'?urdu:en,[lang]);
 const [theme,setTheme]=useState('light'),[tab,setTabState]=useState(menus[role].some(m=>m[0]===initialTab)?initialTab!:'overview');
 const [s,setState]=useState<SchoolState|null>(null),[teacher,setTeacher]=useState(''),[studentId,setStudent]=useState(''),[classId,setClass]=useState('');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[toast,setToast]=useState(''),[form,setForm]=useState<SchoolForm|null>(null),[booking,setBooking]=useState<CampusVisit|true|null>(null),[report,setReport]=useState<{kind:'report'|'invoice';id:string}|null>(null);
 const visitor=useRef(''),pending=useRef(false),mutating=useRef(false),alive=useRef(true);
 const openedEntry=useRef(false);
 const refresh=useCallback(async(force=false)=>{
  if(pending.current||mutating.current||(!force&&document.visibilityState!=='visible'))return;
  pending.current=true;
  try{const r=await fetch('/api/school?'+new URLSearchParams({slug,t:token,visitor:visitor.current,role,...(teacher?{teacherId:teacher}:{})}),{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error??'Connection problem');if(alive.current){setState(d);setError('');}}
  catch(e){if(alive.current)setError(e instanceof Error?e.message:t('School connection unavailable. Retry to refresh.','اسکول سے رابطہ نہیں۔ دوبارہ کوشش کریں۔'))}finally{pending.current=false;}
 },[slug,token,role,teacher,t]);
 useEffect(()=>{alive.current=true;visitor.current=visitorId(slug);try{setTheme(localStorage.getItem('np-school-theme')??'light')}catch{};refresh(true);const timer=setInterval(()=>refresh(),2000);const visible=()=>refresh();document.addEventListener('visibilitychange',visible);return()=>{alive.current=false;clearInterval(timer);document.removeEventListener('visibilitychange',visible)}},[refresh,slug]);
 useEffect(()=>{if(toast){const timer=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(timer)}},[toast]);
 useEffect(()=>{
  if(role!=='parent'||!s||!s.students.length||openedEntry.current||(!initialVisit&&!initialEnquiry))return;
  openedEntry.current=true;
  if(initialVisit){setBooking(true);return;}
  const program=s.classes.find(c=>c.id===initialProgram);
  setForm({title:t('New sample admissions enquiry','نئی نمونہ داخلہ درخواست'),action:'admission',data:{requestId:crypto.randomUUID()},fields:[{key:'name',label:t('Fictional applicant name','فرضی طالب علم کا نام')},{key:'program',label:t('Programme / class','پروگرام یا کلاس'),value:program?.name,options:s.classes.map(c=>({value:c.name,label:c.name}))},{key:'note',label:t('Enquiry details','درخواست کی تفصیل'),type:'textarea',required:false}]});
 },[s,role,initialVisit,initialEnquiry,initialProgram,t]);
 const setTab=(next:string)=>{setTabState(next);const u=new URL(location.href);u.searchParams.set('tab',next);history.replaceState(null,'',u)};
 async function act<T=unknown>(action:string,data:Record<string,unknown>):Promise<T|null>{
  if(mutating.current)return null;mutating.current=true;setBusy(true);setError('');
  try{const r=await fetch('/api/school',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({slug,t:token,visitor:visitor.current,role,action,...data,...(role==='teacher'?{teacherId:teacher||s?.teachers[0].id}:{})})});const d=await r.json();if(!r.ok)throw new Error(d.error??'Save failed');setToast(t(action==='reminder'?'Reminder simulated. No message was sent.':'Saved in the school demo.',action==='reminder'?'یاد دہانی نمونہ ہے۔ حقیقی پیغام نہیں بھیجا گیا۔':'اسکول ڈیمو میں محفوظ ہو گیا۔'));mutating.current=false;await refresh(true);return d.result as T;}
  catch(e){setError(e instanceof Error?e.message:t('Could not save. Retry with the same information.','محفوظ نہیں ہوا۔ انہی معلومات سے دوبارہ کوشش کریں۔'));return null}finally{mutating.current=false;setBusy(false)}
 }
 const open=(f:SchoolForm)=>setForm({...f,data:{requestId:crypto.randomUUID(),...f.data}});
 const selected=s?.students.find(st=>st.id===studentId)??s?.students[0],cl=s?.classes.find(c=>c.id===classId)??s?.classes.find(c=>c.id===selected?.class_id)??s?.classes[0];
 const view=s&&selected&&cl?{s,role,ur,student:selected,cl,teacherId:teacher||s.teachers[0].id,busy,t,act,open,report:(kind:'report'|'invoice',id:string)=>setReport({kind,id})} satisfies SchoolView:null;
 const title=menus[role].find(m=>m[0]===tab)?.[ur?2:1]??'',roleTitle=t(role==='parent'?'Parent portal':role==='school'?'School office':'Teacher workspace',role==='parent'?'والدین پورٹل':role==='school'?'اسکول دفتر':'استاد ورک اسپیس');
 const nav=menus[role].map(([key,en,urdu,icon])=><button key={key} type="button" className={key===tab?'active':''} onClick={()=>setTab(key)} aria-current={key===tab?'page':undefined}><SIcon name={icon}/>{t(en,urdu)}</button>);
 function toggleLang(){const next=ur?'en':'ur';setLang(next);const u=new URL(location.href);u.searchParams.set('lang',next);history.replaceState(null,'',u)}
 return <div className="sc" data-school-theme={theme} dir={ur?'rtl':'ltr'} lang={lang}>
  <aside className="sc-sidebar"><a className="sc-brand" href={`/d/${slug}/parent?t=${encodeURIComponent(token)}`}><span><SIcon name="cap"/></span><span>Campus<span className="sc-brand-accent">flow</span><small>BY NEXUSPOINT</small></span></a><div className="sc-business"><b>{name}</b><small>{t('A connected campus demo','مربوط کیمپس کا ڈیمو')}</small></div><p className="sc-kicker">{roleTitle}</p><nav className="sc-nav" aria-label={roleTitle}>{nav}</nav><div className="sc-disclosure"><SIcon name="book"/><b>{t('Made for your walkthrough','نمونہ پریزنٹیشن کے لیے')}</b><p>{t('Fictional students, staff, fees and academic records. No real admissions, payments or notifications.','طلبہ، عملہ، فیس اور ریکارڈ فرضی ہیں۔ حقیقی داخلہ، ادائیگی یا اطلاع نہیں ہوتی۔')}</p></div><a className="sc-back" href={`/d/${slug}?t=${encodeURIComponent(token)}${ur?'&lang=ur':''}`}>{t('Back to your review report','جائزہ رپورٹ پر واپس جائیں')}</a></aside>
  <div className="sc-main"><header className="sc-top"><p className="sc-crumb">{roleTitle} <span>/</span> <b>{title}</b></p><div className="sc-actions"><select aria-label={t('Demo role','نمونہ کردار')} value={role} onChange={e=>location.assign(`/d/${slug}/${e.target.value}?t=${encodeURIComponent(token)}&lang=${lang}`)}><option value="parent">{t('Parent view','والدین کا منظر')}</option><option value="school">{t('School office','اسکول دفتر')}</option><option value="teacher">{t('Teacher view','استاد کا منظر')}</option></select><button className="sc-icon-btn" onClick={()=>{const next=theme==='light'?'dark':'light';setTheme(next);try{localStorage.setItem('np-school-theme',next)}catch{}}} aria-label={t('Toggle theme','تھیم تبدیل کریں')}><SIcon name="sun"/></button><button className="sc-link" onClick={toggleLang}>{ur?'English':'اردو'}</button><span className="sc-avatar">NP</span></div></header><nav className="sc-mobile-nav" aria-label={roleTitle}>{nav}</nav>
  <main className="sc-content" aria-busy={!s}><div className="sc-heading sc-row"><div><p className="sc-kicker">{t('Every learner, connected','ہر طالب علم، مربوط')}</p><h1>{tab==='overview'?t(role==='parent'?'Welcome back, Khan family':role==='school'?'A good day for your campus':'Good day, '+(s?.teachers.find(te=>te.id===(teacher||s?.teachers[0]?.id))?.name??'teacher'),role==='parent'?'خوش آمدید، خان خاندان':role==='school'?'آپ کے کیمپس کا اچھا دن':'خوش آمدید، استاد'):title}</h1><p>{t('Sample workspace · Pakistan Standard Time (PKT)','نمونہ ورک اسپیس، پاکستان کا معیاری وقت')}</p></div><div className="sc-selectors">{role==='teacher'&&s&&<select aria-label={t('Sample teacher','نمونہ استاد')} value={teacher||s.teachers[0].id} onChange={e=>{setTeacher(e.target.value);setClass('');setStudent('');setState(null)}}>{s.teachers.map(te=><option key={te.id} value={te.id}>{te.name}</option>)}</select>}{s&&selected&&<select aria-label={t('Selected student','منتخب طالب علم')} value={selected.id} onChange={e=>{setStudent(e.target.value);setClass(s.students.find(st=>st.id===e.target.value)?.class_id??'')}}>{s.students.map(st=><option key={st.id} value={st.id}>{st.name}{role!=='parent'?' · '+st.roll:''}</option>)}</select>}{role!=='parent'&&s&&cl&&<select aria-label={t('Selected class','منتخب کلاس')} value={cl.id} onChange={e=>setClass(e.target.value)}>{s.classes.map(cl=><option key={cl.id} value={cl.id}>{cl.name}</option>)}</select>}</div></div>
  {!s?<div className="sc-card"><SchoolEmpty>{error?t('Connection needs attention. Use Retry above.','رابطے میں مسئلہ ہے۔ دوبارہ کوشش کریں۔'):t('Loading your campus…','کیمپس لوڈ ہو رہا ہے…')}</SchoolEmpty></div>:view&&<>
   {tab==='overview'&&<SchoolOverview v={view} setTab={setTab}/>}
   {tab==='attendance'&&<AttendancePanel {...view}/>}
   {tab==='homework'&&<HomeworkPanel {...view}/>}
   {tab==='results'&&<ResultsPanel {...view}/>}
   {tab==='fees'&&<FeesPanel {...view}/>}
   {tab==='admissions'&&<AdmissionsPanel v={view} book={visit=>setBooking(visit??true)}/>}
   {tab==='leave'&&<LeavePanel {...view}/>}
   {tab==='timetable'&&<TimetablePanel {...view}/>}
   {tab==='students'&&<SchoolStudents v={view} select={id=>setStudent(id)}/>}
   {tab==='notices'&&<SchoolNotices {...view}/>}
   {tab==='calendar'&&<SchoolCalendar v={view} book={visit=>setBooking(visit??true)}/>}
   {tab==='inbox'&&<SchoolInbox {...view}/>}
   {tab==='messages'&&<div className="sc-columns"><section className="sc-card sc-chat"><ChatWindow slug={slug} token={token} name={name} lang={lang} prompts={ur?['نمونہ فیس دیکھیں','حاضری کا ریکارڈ','کیمپس ملاقات بک کریں']:['Check sample fees','Show attendance','Book a campus visit']} school/></section><section className="sc-card"><h3>{t('A shared conversation','ایک مربوط گفتگو')}</h3><p className="sc-body">{t('Your assistant uses the same recorded fees, homework and availability as this portal. The school office sees the transcript and can take over.','اسسٹنٹ اسی پورٹل کی ریکارڈ شدہ فیس، ہوم ورک اور دستیاب اوقات استعمال کرتا ہے۔ دفتر گفتگو دیکھ سکتا ہے اور جواب دے سکتا ہے۔')}</p><p className="sc-note">{t('No actual WhatsApp messages are sent from this walkthrough.','اس نمونہ سے حقیقی واٹس ایپ پیغام نہیں جاتا۔')}</p></section></div>}
  </>}
  <footer className="sc-foot">{t('Built by NexusPoint · Synthetic education data · Demo role switching is for presentations, not student authentication.','نیکسس پوائنٹ، فرضی تعلیمی ریکارڈ۔ نمونہ کردار صرف پریزنٹیشن کے لیے، حقیقی طالب علم کی شناخت نہیں۔')}{s&&<small>{t('Last synced: ','تازہ ریکارڈ: ')}{timeLabel(s.server_time,lang)}</small>}</footer></main></div>
  {error&&<div className="sc-error" role="alert"><p>{error}</p><button className="sc-btn secondary small" onClick={()=>refresh(true)}>{t('Retry','دوبارہ کوشش')}</button><button className="sc-icon-btn" aria-label={t('Dismiss error','پیغام بند کریں')} onClick={()=>setError('')}>×</button></div>}
  {toast&&<div className="sc-toast" role="status">{toast}</div>}
  {form&&<SchoolFormModal form={form} ur={ur} busy={busy} onClose={()=>setForm(null)} onSave={async d=>{for(const k of ['start','end'])if(typeof d[k]==='string'&&!/[zZ]|[+-]\d{2}:\d{2}$/.test(d[k] as string))d[k]+='+05:00';for(const [key,target] of [['startTime','startMin'],['endTime','endMin']])if(typeof d[key]==='string'){const [h,m]=(d[key] as string).split(':').map(Number);d[target]=h*60+m;delete d[key];}return !!await act(form.action,d)}}/>}
  {booking&&view&&<CampusBooking v={view} slug={slug} token={token} visitor={visitor.current} visit={booking===true?undefined:booking} onClose={()=>setBooking(null)}/>}
  {report&&view&&<SModal title={t(report.kind==='report'?'Sample report card':'Sample fee document',report.kind==='report'?'نمونہ رپورٹ کارڈ':'نمونہ فیس دستاویز')} onClose={()=>setReport(null)} wide><SchoolReport v={view} name={name} kind={report.kind} id={report.id}/></SModal>}
 </div>;
}
function SchoolOverview({v,setTab}:{v:SchoolView;setTab:(tab:string)=>void}){
 const {s,role,student,t,ur,cl}=v,isParent=role==='parent',today=localDate(),summary=attendanceSummary(s.attendance.filter(a=>a.student_id===student.id)),due=s.invoices.filter(i=>i.student_id===student.id&&!i.paid&&i.status==='issued').reduce((sum,i)=>sum+i.amount,0),tasks=s.homework.filter(h=>h.class_id===student.class_id&&h.published&&!s.submissions.some(sub=>sub.assignment_id===h.id&&sub.student_id===student.id));
 const stats=isParent?[[summary.percent===null?'—':summary.percent+'%',t('Recorded attendance','ریکارڈ شدہ حاضری'),'check',summary.recorded+' '+t('recorded days','ریکارڈ شدہ دن')],[String(tasks.length),t('Homework to submit','باقی ہوم ورک'),'book',t('Published tasks only','صرف شائع شدہ کام')],[feeMoney(due),t('Pending sample fees','باقی نمونہ فیس'),'fee',t('Office verifies payments','دفتر ادائیگی تصدیق کرتا ہے')],[String(s.assessments.filter(a=>a.class_id===student.class_id).length),t('Published assessments','شائع شدہ امتحانات'),'cap',t('Missing marks stay blank','نامعلوم نمبر خالی ہیں')]]:[[String(s.students.length),t('Sample students','نمونہ طلبہ'),'users',String(s.classes.length)+' '+t('classes','کلاسیں')],[String(s.attendance.filter(a=>a.day===today).length),t('Attendance recorded today','آج ریکارڈ شدہ حاضری'),'check',today],[String(role==='school'?s.claims.filter(c=>c.status==='pending').length:s.submissions.filter(sub=>sub.status==='submitted').length),t(role==='school'?'Payments to review':'Responses to review',role==='school'?'ادائیگی کا جائزہ':'جوابات کا جائزہ'),'fee',t('Needs staff review','عملے کا جائزہ باقی')],[String(role==='school'?s.admissions.filter(a=>a.status==='submitted').length:s.homework.filter(h=>!h.published).length),t(role==='school'?'Admissions enquiries':'Homework drafts',role==='school'?'داخلہ درخواستیں':'ہوم ورک مسودے'),'cap',t('Saved in this demo','اس ڈیمو میں محفوظ')]];
 return <><section className="sc-hero"><div><span className="sc-chip">{t('A little clarity, every day','ہر دن، واضح معلومات')}</span><h2>{t(isParent?'A brighter day, together.':role==='school'?'Less paperwork. More learning.':'Make room for better learning.',isParent?'مل کر بہتر کل کی طرف':role==='school'?'کم کاغذی کام، زیادہ تعلیم':'بہتر تعلیم کے لیے جگہ بنائیں')}</h2><p>{isParent?student.name+' · '+s.classes.find(c=>c.id===student.class_id)?.name:t(role==='school'?'Attendance, fees, admissions and conversations in one connected office.':'Your class, schedule and teaching records stay connected to every family.',role==='school'?'حاضری، فیس، داخلہ اور گفتگو ایک مربوط دفتر میں۔':'کلاس، شیڈول اور تعلیم کا ریکارڈ ہر خاندان سے مربوط۔')}</p><button className="sc-btn" onClick={()=>setTab(isParent?'homework':role==='school'?'admissions':'attendance')}>{t(isParent?'Explore learning':role==='school'?'Open admissions':'Open class register',isParent?'تعلیم دیکھیں':role==='school'?'داخلہ دیکھیں':'کلاس رجسٹر کھولیں')}<SIcon name="arrow"/></button></div><SchoolArt/></section><div className="sc-grid four sc-space">{stats.map(([number,label,icon,note])=><div className="sc-card sc-stat" key={label}><div className="sc-row"><strong>{number}</strong><span className="sc-icon-tile"><SIcon name={icon}/></span></div><b>{label}</b><small>{note}</small></div>)}</div>
 <div className="sc-columns"><section className="sc-card"><div className="sc-row"><h3>{t(isParent?'Learning this week':role==='school'?'Office follow-up':'Your classroom',isParent?'اس ہفتے کی تعلیم':role==='school'?'دفتر کی پیروی':'آپ کی کلاس')}</h3><button className="sc-link" onClick={()=>setTab(isParent?'timetable':role==='school'?'inbox':'timetable')}>{t('View all','سب دیکھیں')}</button></div>{isParent?s.homework.filter(h=>h.class_id===student.class_id).slice(0,4).map(h=><div className="sc-list-row" key={h.id}><div className="sc-row"><div><b>{h.title}</b><p>{h.subject} · {t('Due','آخری تاریخ')} {h.due}</p></div><span className="sc-icon-tile"><SIcon name="book"/></span></div></div>):role==='school'?<><div className="sc-list-row"><b>{s.visits.filter(vis=>localDate(new Date(vis.starts_at))===today&&vis.status==='confirmed').length} {t('campus visits today','آج کیمپس ملاقاتیں')}</b><p>{t('Check arrivals in the office calendar.','دفتر کیلنڈر میں پہنچنے کی تصدیق کریں۔')}</p></div><div className="sc-list-row"><b>{s.leaves.filter(l=>l.status==='pending').length} {t('leave requests pending','چھٹی درخواستیں باقی')}</b><button className="sc-link" onClick={()=>setTab('leave')}>{t('Review requests','درخواستوں کا جائزہ')}</button></div><div className="sc-list-row"><b>{s.conversations.filter(c=>c.handoff||c.staff_mode).length} {t('conversations need staff','گفتگو کو عملے کی ضرورت')}</b><p>{t('Assignments and full transcripts are in the inbox.','ان باکس میں مکمل گفتگو اور ذمہ دار عملہ موجود ہے۔')}</p></div></>:<>{s.classes.map(c=><div className="sc-list-row" key={c.id}><b>{c.name}</b><p>{s.students.filter(st=>st.class_id===c.id).length} {t('sample students','نمونہ طلبہ')} · {c.room}</p></div>)}<button className="sc-btn secondary" onClick={()=>setTab('results')}>{t('Prepare assessment results','امتحان نتائج تیار کریں')}</button></>}</section><section className="sc-card"><div className="sc-row"><h3>{t('Campus announcements','کیمپس اعلانات')}</h3><SIcon name="notice"/></div>{s.notices.filter(n=>n.published).slice(0,3).map(n=><div className="sc-list-row" key={n.id}><b>{n.title}</b><p dir="auto">{n.body}</p><small>{dateLabel(n.created_at,ur?'ur':'en')}</small></div>)}{!s.notices.some(n=>n.published)&&<SchoolEmpty>{t('No published announcements.','اعلان شائع نہیں ہوا۔')}</SchoolEmpty>}</section></div></>;
}
function SchoolStudents({v,select}:{v:SchoolView;select:(id:string)=>void}){
 const {s,role,student,t,ur,open,report}=v,[search,setSearch]=useState('');
 return <><div className="sc-row sc-toolbar"><input className="sc-search" aria-label={t('Search students','طلبہ تلاش کریں')} placeholder={t('Search name or roll number','نام یا رول نمبر تلاش کریں')} value={search} onChange={e=>setSearch(e.target.value)}/>{role==='school'&&<button className="sc-btn" onClick={()=>open({title:t('Add a student to this demo family','اس نمونہ خاندان میں طالب علم شامل کریں'),action:'student',data:{},fields:[{key:'name',label:t('Fictional name','فرضی نام')},{key:'classId',label:t('Class','کلاس'),options:s.classes.map(c=>({value:c.id,label:c.name}))}]})}>{t('Add sample student','نمونہ طالب علم شامل کریں')}</button>}</div><div className="sc-students"><section className="sc-card sc-student-list">{s.students.filter(st=>(st.name+' '+st.roll).toLowerCase().includes(search.toLowerCase())).map(st=><button key={st.id} className={st.id===student.id?'active':''} onClick={()=>select(st.id)}><span className="sc-avatar">{st.name.split(' ').map(n=>n[0]).slice(0,2).join('')}</span><span><b>{st.name}</b><small>{st.roll}</small></span></button>)}</section><section className="sc-card"><div className="sc-row"><div><h2>{student.name}</h2><p>{student.roll} · {s.classes.find(c=>c.id===student.class_id)?.name}</p></div><button className="sc-btn secondary" onClick={()=>report('report',student.id)}>{t('View report card','رپورٹ کارڈ دیکھیں')}</button></div><p className="sc-note">{t('Fictional student profile. Published academic information is visible to the linked demo family.','فرضی طالب علم۔ شائع شدہ تعلیمی ریکارڈ منسلک خاندان کو نظر آتا ہے۔')}</p>{role==='school'&&<button className="sc-link sc-body" onClick={()=>open({title:t('Edit sample student','نمونہ طالب علم تبدیل کریں'),action:'student',data:{studentId:student.id},fields:[{key:'name',label:t('Name','نام'),value:student.name},{key:'classId',label:t('Class','کلاس'),value:student.class_id,options:s.classes.map(c=>({value:c.id,label:c.name}))}]})}>{t('Edit student profile','طالب علم تبدیل کریں')}</button>}<h3 className="sc-title">{t('Recent attendance','تازہ حاضری')}</h3>{s.attendance.filter(a=>a.student_id===student.id).slice(0,5).map(a=><div className="sc-row sc-list-row" key={a.id}><b>{a.day}</b><SBadge status={a.status} ur={ur}/></div>)}<h3 className="sc-title">{t('Published results','شائع شدہ نتائج')}</h3>{s.assessments.filter(a=>a.published&&a.class_id===student.class_id).map(a=><div key={a.id} className="sc-list-row"><b>{a.title}</b><p>{a.subject} · {a.grades[student.id]===undefined?t('Marks not recorded','نمبر ریکارڈ نہیں'):a.grades[student.id]+'/'+a.total}</p></div>)}</section></div></>;
}
function SchoolNotices(v:SchoolView){
 const {s,t,ur,open,busy,act}=v;
 const edit=(n?:SchoolState['notices'][number])=>open({title:t('Announcement draft','اعلان کا مسودہ'),action:'notice',data:n?{id:n.id}:{},fields:[{key:'title',label:t('Title','عنوان'),value:n?.title},{key:'body',label:t('Announcement','اعلان'),type:'textarea',value:n?.body}],button:t('Save draft','مسودہ محفوظ کریں')});
 return <><div className="sc-row sc-toolbar"><div><h2>{t('Keep every family in the loop','ہر خاندان کو باخبر رکھیں')}</h2><p>{t('Published notices appear in parent and teacher overviews. No outbound messages are sent.','شائع شدہ اعلان والدین اور استاد پورٹل میں نظر آتا ہے۔ حقیقی پیغام نہیں بھیجا جاتا۔')}</p></div><button className="sc-btn" onClick={()=>edit()}>{t('New announcement','نیا اعلان')}</button></div><div className="sc-grid two">{s.notices.map(n=><article className="sc-card" key={n.id}><div className="sc-row"><h3>{n.title}</h3><SBadge status={n.published?'published':'draft'} ur={ur}/></div><p className="sc-body" dir="auto">{n.body}</p><div className="sc-actions"><button className="sc-btn secondary" onClick={()=>edit(n)}>{t('Edit draft','مسودہ تبدیل کریں')}</button>{!n.published&&<button className="sc-btn" disabled={busy} onClick={()=>act('publish',{kind:'notice',id:n.id})}>{t('Publish announcement','اعلان شائع کریں')}</button>}</div></article>)}</div><section className="sc-card sc-body"><h3>{t('Simulated activity','نمونہ سرگرمی')}</h3>{s.activity.slice(0,10).map((a,i)=><div className="sc-list-row" key={a.at+i}><b>{a.kind.replace('school_','').replaceAll('_',' ')}</b><p>{dateLabel(a.at,ur?'ur':'en')} · {timeLabel(a.at,ur?'ur':'en')}{a.kind==='school_reminder'?' · '+String(a.detail.message):''}</p></div>)}</section></>;
}
function SchoolCalendar({v,book}:{v:SchoolView;book:(visit?:CampusVisit)=>void}){
 const {s,t,ur,busy,act,open}=v,[date,setDate]=useState(localDate()),[week,setWeek]=useState(false),days=Array.from({length:week?7:1},(_,i)=>dayAfter(date,i));
 return <><div className="sc-row sc-toolbar"><div><h2>{t('Campus office calendar','کیمپس دفتر کیلنڈر')}</h2><p>{t('One family per 30-minute slot. Confirmed visits must move before time can be blocked.','ہر ۳۰ منٹ میں ایک خاندان۔ وقت بند کرنے سے پہلے بک شدہ ملاقات کا وقت بدلیں۔')}</p></div><div className="sc-actions"><input aria-label={t('Calendar date','کیلنڈر تاریخ')} type="date" value={date} onChange={e=>setDate(e.target.value||localDate())}/><button className="sc-btn secondary" onClick={()=>setWeek(!week)}>{t(week?'Day view':'Week view',week?'دن کا منظر':'ہفتے کا منظر')}</button><button className="sc-btn" onClick={()=>book()}>{t('Book visit','ملاقات بک کریں')}</button></div></div><div className={'sc-calendar '+(week?'week':'')}>{days.map(d=><section className="sc-card" key={d}><h3>{dateLabel(d+'T12:00:00+05:00',ur?'ur':'en')}</h3>{s.visits.filter(v=>localDate(new Date(v.starts_at))===d).map(visit=><div key={visit.id} className="sc-lesson"><div className="sc-row"><b>{timeLabel(visit.starts_at,ur?'ur':'en')}</b><SBadge status={visit.status} ur={ur}/></div><small>{s.families.find(f=>f.id===visit.family_id)?.visitor.slice(0,8)} · {visit.source}</small>{visit.status==='confirmed'&&<div className="sc-actions"><button className="sc-link" onClick={()=>book(visit)}>{t('Reschedule','وقت بدلیں')}</button><button className="sc-btn small" disabled={busy} onClick={()=>act('visit_status',{id:visit.id,status:'arrived'})}>{t('Check in','پہنچ گئے')}</button></div>}{visit.status==='arrived'&&<button className="sc-link" disabled={busy} onClick={()=>act('visit_status',{id:visit.id,status:'completed'})}>{t('Complete','مکمل کریں')}</button>}</div>)}{!s.visits.some(v=>localDate(new Date(v.starts_at))===d)&&<SchoolEmpty>{t('No campus visits','کیمپس ملاقات نہیں')}</SchoolEmpty>}</section>)}</div><div className="sc-card sc-body"><div className="sc-row"><h3>{t('Blocked office times','دفتر کے بند اوقات')}</h3><button className="sc-btn secondary" onClick={()=>open({title:t('Block office time','دفتر کا وقت بند کریں'),action:'block',data:{},fields:[{key:'start',label:t('From (PKT)','آغاز، پاکستانی وقت'),type:'datetime-local'},{key:'end',label:t('To (PKT)','اختتام، پاکستانی وقت'),type:'datetime-local'},{key:'reason',label:t('Reason','وجہ')}]})}>{t('Block time','وقت بند کریں')}</button></div>{s.blocks.map(b=><div className="sc-row sc-list-row" key={b.id}><div><b>{b.reason}</b><p>{dateLabel(b.starts_at)} {timeLabel(b.starts_at)} → {timeLabel(b.ends_at)}</p></div><button className="sc-link" disabled={busy} onClick={()=>act('block',{id:b.id})}>{t('Release time','وقت کھولیں')}</button></div>)}{!s.blocks.length&&<SchoolEmpty>{t('No additional office blocks.','کوئی اضافی بند وقت نہیں۔')}</SchoolEmpty>}</div></>;
}
function SchoolReport({v,name,kind,id}:{v:SchoolView;name:string;kind:'report'|'invoice';id:string}){
 const {s,t,ur}=v,invoice=s.invoices.find(i=>i.id===id),student=s.students.find(st=>st.id===(kind==='report'?id:invoice?.student_id)),marks=s.assessments.filter(a=>a.published&&a.class_id===student?.class_id),claim=s.claims.find(c=>c.invoice_id===id&&c.status==='verified'),attendance=s.attendance.filter(a=>a.student_id===student?.id),summary=attendanceSummary(attendance);
 if(!student)return <SchoolEmpty>{t('Student information is unavailable.','طالب علم کی معلومات نہیں۔')}</SchoolEmpty>;
 return <div className="sc-report"><div className="sc-report-head"><p className="sc-kicker">NEXUSPOINT · CAMPUSFLOW</p><h2>{name}</h2><h3>{t(kind==='report'?'Sample academic report card':invoice?.paid?'Sample payment receipt':'Sample fee challan',kind==='report'?'نمونہ تعلیمی رپورٹ کارڈ':invoice?.paid?'نمونہ ادائیگی رسید':'نمونہ فیس چالان')}</h3><p>{student.name} · {student.roll} · {s.classes.find(cl=>cl.id===student.class_id)?.name}</p><p>{t('Generated','تیار کردہ')} {localDate()} · {t('Fictional data for an outreach demonstration','آؤٹ ریچ ڈیمو کے لیے فرضی معلومات')}</p></div>{kind==='report'?<><h3>{t('Published assessments','شائع شدہ امتحانات')}</h3><table><thead><tr><th>{t('Assessment / subject','امتحان یا مضمون')}</th><th>{t('Date','تاریخ')}</th><th>{t('Marks','نمبر')}</th><th>{t('Teacher','استاد')}</th></tr></thead><tbody>{marks.map(a=><tr key={a.id}><td><b>{a.title}</b><small className="sc-block">{a.subject}</small></td><td>{a.exam_date}</td><td>{a.grades[student.id]===undefined?t('Not recorded','ریکارڈ نہیں'):a.grades[student.id]+' / '+a.total}</td><td>{s.teachers.find(te=>te.id===a.teacher_id)?.name}</td></tr>)}</tbody></table>{!marks.length&&<p>{t('No published assessments.','کوئی شائع شدہ امتحان نہیں۔')}</p>}<h3>{t('Recorded attendance','ریکارڈ شدہ حاضری')}</h3><p>{summary.recorded} {t('recorded days','ریکارڈ شدہ دن')} · {summary.present} {t('present / late','حاضر یا تاخیر')} · {summary.absent} {t('absent','غیر حاضر')}. {t('Unrecorded dates are unknown. Excused days are excluded from the attendance percentage.','بغیر ریکارڈ دن نامعلوم ہیں۔ منظور شدہ چھٹی حاضری فیصد میں شامل نہیں۔')}</p><table><thead><tr><th>{t('Date','تاریخ')}</th><th>{t('Status','حالت')}</th><th>{t('Note','نوٹ')}</th></tr></thead><tbody>{attendance.map(a=><tr key={a.id}><td>{a.day}</td><td><SBadge status={a.status} ur={ur}/></td><td>{a.note||'—'}</td></tr>)}</tbody></table></>:invoice&&<><div className="sc-note"><b>{invoice.period}</b><p>{feeMoney(invoice.amount)} · {t('Due','آخری تاریخ')} {invoice.due}</p><p>{t('Document ID','دستاویز نمبر')}: {invoice.id}</p><p>{t('Status','حالت')}: {invoice.paid?t('Verified demo payment','تصدیق شدہ نمونہ ادائیگی'):invoice.status==='void'?t('Void','منسوخ'):t('Payment not verified','ادائیگی کی تصدیق نہیں')}</p>{claim&&<><p>{t('Reference','حوالہ')}: {claim.reference}</p><p>{t('Office verified','دفتر کی تصدیق')}: {claim.verified_at&&dateLabel(claim.verified_at)}</p></>}</div><p>{t('This is an illustrative fee document, not a bank deposit slip or proof of a real payment.','یہ نمونہ فیس دستاویز ہے، بینک چالان یا حقیقی ادائیگی کا ثبوت نہیں۔')}</p></>}<p className="sc-note">{t('Only recorded, published information is shown. This is not an official school certificate.','صرف ریکارڈ شدہ شائع معلومات دکھائی گئی ہیں۔ یہ سرکاری تعلیمی سند نہیں۔')}</p><div className="sc-modal-foot"><button className="sc-btn" onClick={()=>window.print()}>{t('Print / save as PDF','پرنٹ یا پی ڈی ایف محفوظ کریں')}</button></div></div>;
}
