'use client';
import { useEffect,useState } from 'react';
import type { SchoolState,SchoolRole,Student,SchoolClass,Homework,Assessment } from '@/lib/school-types';
import { localDate } from '@/lib/healthcare-types';
import { SIcon,SModal,type SchoolForm } from './SchoolUI';
export type SchoolView={s:SchoolState;role:SchoolRole;ur:boolean;student:Student;cl:SchoolClass;teacherId:string;busy:boolean;t:(en:string,ur:string)=>string;act:<T=unknown>(action:string,d:Record<string,unknown>)=>Promise<T|null>;open:(f:SchoolForm)=>void;report:(kind:'report'|'invoice',id:string)=>void};
const days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],daysUr=['اتوار','پیر','منگل','بدھ','جمعرات','جمعہ','ہفتہ'];
export function SchoolEmpty({children}:{children:React.ReactNode}){return <div className="sc-empty"><SIcon name="book"/>{children}</div>}
const statusUr:Record<string,string>={present:'حاضر',absent:'غیر حاضر',late:'تاخیر',excused:'منظور شدہ چھٹی',published:'شائع شدہ',draft:'مسودہ',submitted:'جمع شدہ',reviewed:'جائزہ لیا گیا',pending:'زیر جائزہ',verified:'تصدیق شدہ',rejected:'مسترد',approved:'منظور',declined:'نامنظور',confirmed:'تصدیق شدہ',arrived:'پہنچ گئے',completed:'مکمل',cancelled:'منسوخ',no_show:'نہیں آئے',reviewing:'زیر جائزہ',accepted:'قبول',closed:'بند',issued:'جاری',void:'منسوخ',paid:'ادا شدہ'};
export function SBadge({status,ur}:{status:string;ur:boolean}){return <span className={'sc-badge '+status}>{ur?(statusUr[status]??status):status.replaceAll('_',' ')}</span>}
export function AttendancePanel(v:SchoolView){
 const {s,role,student,cl,t,ur,busy,act}=v;
 const [date,setDate]=useState(localDate()),[draft,setDraft]=useState<Record<string,string>>({});
 useEffect(()=>{setDraft({})},[cl.id,date,student.id]);
 const students=role==='parent'?[student]:s.students.filter(st=>st.class_id===cl.id);
 const rows=s.attendance.filter(a=>students.some(st=>st.id===a.student_id));
 return <><div className="sc-row sc-toolbar"><div><h2>{t('Attendance register','حاضری رجسٹر')}</h2><p>{t('Blank means not recorded. It is never counted as absent.','خالی کا مطلب ریکارڈ موجود نہیں۔ اسے غیر حاضری نہیں شمار کیا جاتا۔')}</p></div>{role!=='parent'&&<label>{t('Recorded day (PKT)','ریکارڈ کا دن')}<input type="date" value={date} max={localDate()} onChange={e=>setDate(e.target.value)}/></label>}</div>
 {role==='parent'?<div className="sc-card sc-table-wrap"><table><thead><tr><th>{t('Date','تاریخ')}</th><th>{t('Status','حالت')}</th><th>{t('Note','نوٹ')}</th></tr></thead><tbody>{rows.map(a=><tr key={a.id}><td>{a.day}</td><td><SBadge status={a.status} ur={ur}/></td><td>{a.note||'—'}</td></tr>)}</tbody></table>{!rows.length&&<SchoolEmpty>{t('No attendance has been recorded.','حاضری ریکارڈ نہیں ہوئی۔')}</SchoolEmpty>}</div>:<div className="sc-card"><div className="sc-row"><h3>{cl.name}</h3><button className="sc-btn secondary small" onClick={()=>setDraft(Object.fromEntries(students.map(st=>[st.id,'present'])))}>{t('Mark all present','سب کو حاضر کریں')}</button></div><div className="sc-table-wrap"><table><thead><tr><th>{t('Student','طالب علم')}</th><th>{t('Roll number','رول نمبر')}</th><th>{t('Attendance','حاضری')}</th></tr></thead><tbody>{students.map(st=>{const recorded=rows.find(a=>a.student_id===st.id&&a.day===date);return <tr key={st.id}><td><b>{st.name}</b></td><td>{st.roll}</td><td><select aria-label={t('Attendance for ','حاضری ')+st.roll} value={draft[st.id]??recorded?.status??''} onChange={e=>setDraft({...draft,[st.id]:e.target.value})}><option value="">{t('Not recorded','ریکارڈ نہیں')}</option>{['present','absent','late','excused'].map(x=><option key={x} value={x}>{ur?statusUr[x]:x}</option>)}</select></td></tr>})}</tbody></table></div><div className="sc-actions"><button className="sc-btn" disabled={busy} onClick={async()=>{const r=await act('attendance',{classId:cl.id,day:date,rows:students.map(st=>({studentId:st.id,status:draft[st.id]??rows.find(a=>a.student_id===st.id&&a.day===date)?.status??'',note:rows.find(a=>a.student_id===st.id&&a.day===date)?.note??''})).filter(r=>r.status)});if(r)setDraft({});}}>{t('Save attendance','حاضری محفوظ کریں')}</button></div></div>}</>;
}
export function HomeworkPanel(v:SchoolView){
 const {s,role,cl,student,t,ur,open,act,busy}=v;
 const tasks=s.homework.filter(h=>h.class_id===(role==='parent'?student.class_id:cl.id));
 const edit=(h?:Homework)=>open({title:t(h?'Edit homework draft':'New homework draft',h?'ہوم ورک مسودہ تبدیل کریں':'نیا ہوم ورک مسودہ'),action:'homework',data:{classId:cl.id,...(h?{id:h.id}:{})},fields:[{key:'title',label:t('Title','عنوان'),value:h?.title},{key:'subject',label:t('Subject','مضمون'),value:h?.subject??s.teachers.find(te=>te.id===cl.teacher_id)?.subject},{key:'due',label:t('Due date','آخری تاریخ'),type:'date',value:h?.due??localDate()},{key:'instructions',label:t('Instructions','ہدایات'),type:'textarea',value:h?.instructions}],button:t('Save draft','مسودہ محفوظ کریں')});
 return <><div className="sc-row sc-toolbar"><div><h2>{t('Learning, one task at a time','ہر کام سے نئی تعلیم')}</h2><p>{t('Only published assignments reach the parent portal.','صرف شائع شدہ ہوم ورک والدین پورٹل میں دکھایا جاتا ہے۔')}</p></div>{role!=='parent'&&<button className="sc-btn" onClick={()=>edit()}>{t('New homework','نیا ہوم ورک')}</button>}</div><div className="sc-grid two">{tasks.map(h=>{const own=s.submissions.find(sub=>sub.assignment_id===h.id&&sub.student_id===student.id);const submissions=s.submissions.filter(sub=>sub.assignment_id===h.id);return <article className="sc-card" key={h.id}><div className="sc-row"><span className="sc-icon-tile"><SIcon name="book"/></span><SBadge status={h.published?'published':'draft'} ur={ur}/></div><h3 className="sc-title">{h.title}</h3><p>{h.subject} · {t('Due','آخری تاریخ')} {h.due}</p><p className="sc-body" dir="auto">{h.instructions}</p>{role==='parent'?<><p className="sc-note">{own?<><SBadge status={own.status} ur={ur}/> {own.text}{own.feedback&&<span className="sc-feedback">{t('Teacher feedback: ','استاد کا تبصرہ: ')+own.feedback}</span>}</>:t('No response submitted yet.','ابھی جواب جمع نہیں ہوا۔')}</p><button className="sc-btn secondary" onClick={()=>open({title:t('Submit sample homework','نمونہ ہوم ورک جمع کریں'),action:'submission',data:{studentId:student.id,assignmentId:h.id},fields:[{key:'text',label:t('Sample response','نمونہ جواب'),type:'textarea',value:own?.text}],button:t('Submit response','جواب جمع کریں')})}>{t(own?'Edit response':'Submit response',own?'جواب تبدیل کریں':'جواب جمع کریں')}</button></>:<><div className="sc-actions"><button className="sc-btn secondary small" onClick={()=>edit(h)}>{t('Edit draft','مسودہ تبدیل کریں')}</button>{!h.published&&<button className="sc-btn small" disabled={busy} onClick={()=>act('publish',{kind:'homework',id:h.id})}>{t('Publish homework','ہوم ورک شائع کریں')}</button>}</div><details className="sc-details"><summary>{submissions.length} {t('student responses','طلبہ کے جوابات')}</summary>{submissions.map(sub=><div className="sc-list-row" key={sub.id}><b>{s.students.find(st=>st.id===sub.student_id)?.name} · {s.students.find(st=>st.id===sub.student_id)?.roll}</b><p dir="auto">{sub.text}</p><p>{sub.feedback}</p><button className="sc-link" onClick={()=>open({title:t('Review response','جواب کا جائزہ'),action:'submission',data:{studentId:sub.student_id,assignmentId:h.id},fields:[{key:'feedback',label:t('Feedback','تبصرہ'),type:'textarea',value:sub.feedback}],button:t('Save feedback','تبصرہ محفوظ کریں')})}>{t('Review response','جواب کا جائزہ')}</button></div>)}</details></>}</article>})}</div>{!tasks.length&&<div className="sc-card"><SchoolEmpty>{t('No homework here yet.','ابھی کوئی ہوم ورک نہیں۔')}</SchoolEmpty></div>}</>;
}
export function AssessmentEditor({v,assessment,onClose}:{v:SchoolView;assessment?:Assessment;onClose:()=>void}){
 const {s,cl,t,busy,act}=v;
 const students=s.students.filter(st=>st.class_id===cl.id);
 const [retry]=useState(()=>crypto.randomUUID());
 return <SModal title={t(assessment?'Edit assessment draft':'New assessment draft',assessment?'امتحان مسودہ تبدیل کریں':'نیا امتحان مسودہ')} onClose={onClose} wide><p className="sc-note">{t('Leave missing marks blank. Save a draft, then explicitly publish it from the results list. Editing a published result returns it to draft.','نامعلوم نمبر خالی چھوڑیں۔ مسودہ محفوظ کریں، پھر نتائج کی فہرست سے شائع کریں۔ شائع شدہ نتیجہ تبدیل کرنے سے دوبارہ مسودہ بنے گا۔')}</p><form onSubmit={async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget)),grades:Record<string,number>={};for(const st of students)if(f[st.id]!=='')grades[st.id]=Number(f[st.id]);const out=await act('assessment',{requestId:retry,classId:cl.id,...(assessment?{id:assessment.id}:{}),title:f.title,subject:f.subject,total:Number(f.total),examDate:f.examDate,comment:f.comment,grades});if(out)onClose();}}><div className="sc-fields"><label>{t('Title','عنوان')}<input name="title" required maxLength={150} defaultValue={assessment?.title}/></label><label>{t('Subject','مضمون')}<input name="subject" required maxLength={150} defaultValue={assessment?.subject??s.teachers.find(te=>te.id===cl.teacher_id)?.subject}/></label><label>{t('Exam date','امتحان کی تاریخ')}<input name="examDate" type="date" required defaultValue={assessment?.exam_date??localDate()}/></label><label>{t('Total marks','کل نمبر')}<input name="total" type="number" min={1} max={1000} required defaultValue={assessment?.total??50}/></label></div><div className="sc-table-wrap"><table><thead><tr><th>{t('Student','طالب علم')}</th><th>{t('Recorded marks','ریکارڈ شدہ نمبر')}</th></tr></thead><tbody>{students.map(st=><tr key={st.id}><td>{st.name}<small className="sc-block">{st.roll}</small></td><td><input type="number" step=".5" min={0} max={1000} aria-label={t('Marks for ','نمبر ')+st.roll} name={st.id} defaultValue={assessment?.grades[st.id]??''} placeholder={t('Not recorded','ریکارڈ نہیں')}/></td></tr>)}</tbody></table></div><label>{t('Class feedback','کلاس کا تبصرہ')}<textarea name="comment" maxLength={3000} defaultValue={assessment?.comment}/></label><div className="sc-modal-foot"><button type="button" className="sc-btn secondary" onClick={onClose}>{t('Close','بند کریں')}</button><button className="sc-btn" disabled={busy}>{t('Save draft','مسودہ محفوظ کریں')}</button></div></form></SModal>;
}
export function ResultsPanel(v:SchoolView){
 const {s,role,cl,student,t,ur,act,busy,report}=v;
 const [editor,setEditor]=useState<Assessment|true|null>(null);
 const rows=s.assessments.filter(a=>a.class_id===(role==='parent'?student.class_id:cl.id));
 return <><div className="sc-row sc-toolbar"><div><h2>{t('A clear view of learning','تعلیم کا واضح ریکارڈ')}</h2><p>{t('Recorded marks only. Missing marks stay blank.','صرف ریکارڈ شدہ نمبر۔ نامعلوم نمبر خالی رہتے ہیں۔')}</p></div><div className="sc-actions">{role!=='parent'&&<button className="sc-btn" onClick={()=>setEditor(true)}>{t('New assessment','نیا امتحان')}</button>}<button className="sc-btn secondary" onClick={()=>report('report',student.id)}>{t('Print report card','رپورٹ کارڈ پرنٹ کریں')}</button></div></div><div className="sc-grid two">{rows.map(a=><article className="sc-card" key={a.id}><div className="sc-row"><span className="sc-icon-tile"><SIcon name="cap"/></span><SBadge status={a.published?'published':'draft'} ur={ur}/></div><h3 className="sc-title">{a.title}</h3><p>{a.subject} · {a.exam_date}</p>{role==='parent'?<div className="sc-mark">{a.grades[student.id]??t('Not recorded','ریکارڈ نہیں')}<small> / {a.total}</small></div>:<p className="sc-body">{Object.keys(a.grades).length} / {s.students.filter(st=>st.class_id===a.class_id).length} {t('students with recorded marks','طلبہ کے نمبر ریکارڈ ہیں')}</p>}<p dir="auto">{a.comment||t('No comment recorded.','تبصرہ ریکارڈ نہیں۔')}</p>{role!=='parent'&&<div className="sc-actions"><button className="sc-btn secondary small" onClick={()=>setEditor(a)}>{t('Edit draft','مسودہ تبدیل کریں')}</button>{!a.published&&<button className="sc-btn small" disabled={busy} onClick={()=>act('publish',{kind:'assessment',id:a.id})}>{t('Publish results','نتائج شائع کریں')}</button>}</div>}</article>)}</div>{!rows.length&&<div className="sc-card"><SchoolEmpty>{t('No results have been published.','نتائج شائع نہیں ہوئے۔')}</SchoolEmpty></div>}{editor&&<AssessmentEditor v={v} assessment={editor===true?undefined:editor} onClose={()=>setEditor(null)}/>}</>;
}
const clock=(m:number)=>String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0');
export function TimetablePanel(v:SchoolView){
 const {s,cl,role,student,t,ur,open,act,busy}=v,lessons=s.lessons.filter(l=>l.class_id===(role==='parent'?student.class_id:cl.id));
 return <><div className="sc-row sc-toolbar"><div><h2>{t('Your week at a glance','ہفتے کا شیڈول')}</h2><p>{t('Illustrative classes and rooms. All times are PKT.','نمونہ کلاسیں اور کمرے۔ تمام اوقات پاکستانی ہیں۔')}</p></div>{role==='school'&&<button className="sc-btn" onClick={()=>open({title:t('Add timetable lesson','شیڈول میں سبق شامل کریں'),action:'lesson',data:{classId:cl.id},fields:[{key:'day',label:t('Day number · 1 Monday to 6 Saturday','دن نمبر، ۱ پیر تا ۶ ہفتہ'),type:'number',min:1,max:6,value:1},{key:'lessonTeacherId',label:t('Teacher','استاد'),options:s.teachers.map(te=>({value:te.id,label:te.name}))},{key:'subject',label:t('Subject','مضمون')},{key:'room',label:t('Room','کمرہ'),value:cl.room},{key:'startTime',label:t('Start time (PKT)','آغاز، پاکستانی وقت'),type:'time',value:'13:00'},{key:'endTime',label:t('End time (PKT)','اختتام، پاکستانی وقت'),type:'time',value:'13:30'}]})}>{t('Add lesson','سبق شامل کریں')}</button>}</div><div className="sc-week">{[1,2,3,4,5,6].map(day=><div key={day} className="sc-day"><h3>{ur?daysUr[day]:days[day]}</h3>{lessons.filter(l=>l.day===day).map(l=><div className="sc-lesson" key={l.id}><small>{clock(l.start_min)}–{clock(l.end_min)}</small><b>{l.subject}</b><small>{s.teachers.find(te=>te.id===l.teacher_id)?.name}</small><small>{l.room}</small>{role==='school'&&<button className="sc-link" disabled={busy} onClick={()=>act('lesson',{id:l.id,classId:cl.id})}>{t('Remove lesson','سبق حذف کریں')}</button>}</div>)}{!lessons.some(l=>l.day===day)&&<p>{t('No lessons recorded','سبق ریکارڈ نہیں')}</p>}</div>)}</div></>;
}
