"use client";
import { useEffect, useState, type ReactNode } from "react";
import type { Business } from "@/lib/db";
import type { Lang } from "@/lib/i18n";
import { SIcon } from "./SchoolUI";
import "./school-landing.css";

export type LandingProgram = { id: string; name: string };
type SchoolBusiness = Pick<Business, "slug" | "token" | "name"> & {
  profile: { facts: Business["profile"]["facts"] };
  xray: { praise: NonNullable<Business["xray"]>["praise"] } | null;
};

export default function SchoolLanding({ business: b, programs, programsUnavailable, initialLang, embedded = false }: {
  business: SchoolBusiness; programs: LandingProgram[]; programsUnavailable: boolean; initialLang: Lang; embedded?: boolean;
}) {
  const [lang, setLang] = useState(initialLang), [theme, setTheme] = useState("light"), [menu, setMenu] = useState(false);
  const [search, setSearch] = useState(""), [category, setCategory] = useState("all");
  const ur = lang === "ur", t = (en: string, u: string) => ur ? u : en;
  const f = b.profile.facts, college = /college/i.test(f.category ?? b.name), academy = /academy|tuition|coaching|training/i.test(f.category ?? b.name);
  const kind = college ? t("College", "کالج") : academy ? t("Academy", "اکیڈمی") : t("School", "اسکول");
  const initials = b.name.split(/[\s-]+/).filter(Boolean).slice(0, 2).map(s => s[0]).join("").toUpperCase();
  const base = `/d/${b.slug}`, query = `?t=${encodeURIComponent(b.token)}${ur ? "&lang=ur" : ""}`;
  const portal = (tab = "overview", action = "") => `${base}/parent${query}&tab=${tab}${action}`;
  const maps = /^https:\/\/(www\.)?google\.(com|com\.pk)\/maps\//i.test(f.maps_url) ? f.maps_url : `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(f.address ?? b.name + " Quetta")}`;
  const group = (p: LandingProgram) => /pre-medical/i.test(p.name) ? "medical" : /pre-engineering/i.test(p.name) ? "engineering" : "general";
  const categories = [...new Set(programs.map(group))];
  const groupName = (key: string) => key === "medical" ? t("Pre-medical", "پری میڈیکل") : key === "engineering" ? t("Pre-engineering", "پری انجینئرنگ") : t("Classes & courses", "کلاسیں اور کورسز");
  const shown = programs.filter(p => (category === "all" || category === group(p)) && p.name.toLowerCase().includes(search.trim().toLowerCase()));
  const praise = b.xray?.praise.filter(p => p.quotes.length).slice(0, 3) ?? [];
  const nav = [["programs", t("Programs", "پروگرام")], ["learning", t("Learning", "تعلیم")], ["admissions", t("Admissions", "داخلہ")], ["visit", t("Visit us", "کیمپس")]];
  useEffect(() => { try { setTheme(localStorage.getItem("np-website-theme") === "dark" ? "dark" : "light"); } catch {} }, []);
  useEffect(() => { const key = (e: KeyboardEvent) => { if (e.key === "Escape") setMenu(false); }; document.addEventListener("keydown", key); return () => document.removeEventListener("keydown", key); }, []);
  function toggleLang() { const next = ur ? "en" : "ur"; setLang(next); setMenu(false); const u = new URL(location.href); u.searchParams.set("lang", next); history.replaceState(null, "", u); }
  function toggleTheme() { const next = theme === "light" ? "dark" : "light"; setTheme(next); try { localStorage.setItem("np-website-theme", next); } catch {} }
  function Link({ href, children, className = "", external = false }: { href: string; children: ReactNode; className?: string; external?: boolean }) {
    return <a href={href} className={className} target={external ? "_blank" : embedded && !href.startsWith("#") ? "_top" : undefined} rel={external ? "noopener noreferrer" : undefined} onClick={() => setMenu(false)}>{children}</a>;
  }
  const Arrow = () => <SIcon name="arrow" />;
  return <div className="sl" data-school-landing-theme={theme} dir={ur ? "rtl" : "ltr"} lang={lang}>
    <a className="sl-skip" href="#sl-main">{t("Skip to content", "مرکزی مواد پر جائیں")}</a>
    <div className="sl-notice"><span>{t("A website concept for your next chapter", "آپ کے اگلے قدم کے لیے ویب سائٹ کا نمونہ")}</span><Link href={base + query}>{t("Private preview by NexusPoint", "نیکسس پوائنٹ کا نجی نمونہ")} ↗</Link></div>
    <header className="sl-header"><div className="sl-wrap sl-nav-row">
      <a className="sl-brand" href="#sl-main"><span className="sl-crest"><SIcon name="book" /></span><span><b dir="auto">{b.name}</b><small>{kind} · {t("Quetta", "کوئٹہ")}</small></span></a>
      <nav className="sl-desktop-nav" aria-label={t("Main navigation", "مرکزی نیویگیشن")}>{nav.map(([id, label]) => <Link key={id} href={"#" + id}>{label}</Link>)}</nav>
      <div className="sl-nav-actions"><button type="button" className="sl-icon-btn" onClick={toggleTheme} aria-label={theme === "light" ? t("Use dark theme", "تاریک رنگ استعمال کریں") : t("Use light theme", "روشن رنگ استعمال کریں")}><SIcon name="sun" /></button><button type="button" className="sl-lang" onClick={toggleLang}>{ur ? "English" : "اردو"}</button><Link className="sl-btn sl-nav-portal" href={portal()}>{t("Parent portal", "والدین پورٹل")}<Arrow /></Link><button className="sl-icon-btn sl-menu-toggle" type="button" aria-expanded={menu} aria-controls="sl-mobile-nav" aria-label={t("Toggle navigation", "مینو کھولیں یا بند کریں")} onClick={() => setMenu(!menu)}>{menu ? "×" : "☰"}</button></div>
    </div>{menu && <nav id="sl-mobile-nav" className="sl-mobile-nav" aria-label={t("Mobile navigation", "موبائل نیویگیشن")}>{nav.map(([id, label]) => <Link key={id} href={"#" + id}>{label}</Link>)}<Link href={portal()}>{t("Parent portal", "والدین پورٹل")}</Link></nav>}</header>
    <main id="sl-main">
      <section className="sl-hero sl-wrap">
        <div className="sl-hero-copy"><p className="sl-eyebrow"><span />{t("Curiosity today. Possibility tomorrow.", "آج کا تجسس، کل کے امکانات")}</p>
          <h1>{t("The next chapter", "اگلا باب")}<br /><span className="sl-highlight">{t("starts here.", "یہیں سے شروع ہوتا ہے۔")}</span></h1>
          <p className="sl-lead">{t("Explore learning at ", "تعلیم کی نئی راہیں، ")}<b dir="auto">{b.name}</b>{t(". Discover sample programs, plan a campus visit, and keep your family connected.", " کے ساتھ۔ نمونہ پروگرام دیکھیں، کیمپس ملاقات طے کریں اور خاندان کو باخبر رکھیں۔")}</p>
          <div className="sl-actions"><Link className="sl-btn" href="#programs">{t("Explore programs", "پروگرام دیکھیں")}<Arrow /></Link><Link className="sl-btn sl-outline" href={portal("admissions", "&visit=1")}><SIcon name="calendar" />{t("Plan a campus visit", "کیمپس ملاقات طے کریں")}</Link></div>
          <div className="sl-hero-foot"><span className="sl-seal" aria-hidden="true"><SIcon name="cap" /></span><div>{f.rating !== null ? <><b><span className="sl-stars" aria-label={`${f.rating} / 5`}>★</span> <bdi>{f.rating} / 5</bdi></b><p>{f.reviews != null ? <bdi>{f.reviews.toLocaleString("en-US")} {t("Google reviews", "گوگل ریویوز")}</bdi> : t("Google listing rating", "گوگل پروفائل کی ریٹنگ")}</p></> : <><b>{t("Discover your next step", "اپنا اگلا قدم دریافت کریں")}</b><p>{t("Ask the admissions team", "داخلہ ٹیم سے بات کریں")}</p></>}</div></div>
        </div>
        <div className="sl-hero-visual"><span className="sl-orbit" aria-hidden="true" /><svg className="sl-spark" viewBox="0 0 100 100" aria-hidden="true"><path d="M50 0v100M0 50h100M15 15l70 70M15 85l70-70" /></svg><figure><img src="/school/learning.webp" width="1536" height="1024" fetchPriority="high" alt={t("Illustrative adult students learning together in a fictional classroom", "فرضی تعلیمی ماحول میں مل کر پڑھتے بالغ طلبہ کی نمائشی تصویر")} /><figcaption>{t("Illustrative learning photography", "تعلیمی ماحول کی نمائشی تصویر")}</figcaption></figure>
          <Link href={portal("admissions", "&visit=1")} className="sl-visit-card"><span className="sl-icon-tile"><SIcon name="calendar" /></span><span><small>{t("Your next step", "آپ کا اگلا قدم")}</small><b>{t("Come say hello", "آئیں، ملاقات کریں")}</b><small>{t("Check campus visit times", "ملاقات کے اوقات دیکھیں")}</small></span><Arrow /></Link>
          <div className="sl-visual-tag"><SIcon name="book" />{t("A little curiosity goes a long way", "تجسس سے نئی راہیں کھلتی ہیں")}</div>
        </div>
      </section>
      <div className="sl-path-strip sl-wrap">{[["book", "Explore your options", "اپنے اختیارات دیکھیں", "Sample programs & classes", "نمونہ پروگرام اور کلاسیں", "#programs"], ["calendar", "Meet the campus", "کیمپس سے واقف ہوں", "A visit at a time that works", "اپنی سہولت کے مطابق ملاقات", portal("admissions", "&visit=1")], ["users", "Stay connected", "باخبر رہیں", "One place for your family", "خاندان کے لیے ایک جگہ", "#family"]].map(([icon, en, u, sub, subUr, href]) => <Link key={en} href={href}><span className="sl-icon-tile"><SIcon name={icon} /></span><span><b>{t(en, u)}</b><small>{t(sub, subUr)}</small></span><Arrow /></Link>)}</div>
      <section id="programs" className="sl-section sl-wrap"><div className="sl-section-head"><div><p className="sl-eyebrow">{t("Find your direction", "اپنی راہ منتخب کریں")}</p><h2>{t("Big possibilities.", "وسیع امکانات۔")}<br />{t("A clear starting point.", "ایک واضح پہلا قدم۔")}</h2></div><p>{t("Explore the sample classes in this connected demo. Confirm actual offerings, eligibility and fees with the office before applying.", "اس مربوط ڈیمو کی نمونہ کلاسیں دیکھیں۔ حقیقی پروگرام، اہلیت اور فیس دفتر سے معلوم کریں۔")}</p></div>
        <div className="sl-program-tools"><div className="sl-filters" role="group" aria-label={t("Program categories", "پروگرام کی اقسام")}><button type="button" aria-pressed={category === "all"} onClick={() => setCategory("all")}>{t("All programs", "تمام پروگرام")}</button>{categories.length > 1 && categories.map(key => <button key={key} type="button" aria-pressed={category === key} onClick={() => setCategory(key)}>{groupName(key)}</button>)}</div><label className="sl-search"><SIcon name="search" /><input aria-label={t("Search programs", "پروگرام تلاش کریں")} placeholder={t("Find a program…", "پروگرام تلاش کریں…")} value={search} onChange={e => setSearch(e.target.value)} type="search" /></label></div>
        <p className="sl-small">{t("Illustrative programs from this school's demo", "اس ادارے کے ڈیمو سے نمونہ پروگرام")}</p>
        <div className="sl-program-grid">{shown.map((p, i) => <article className="sl-program" key={p.id} data-program={group(p)}><div className="sl-row"><span className="sl-program-icon"><SIcon name={group(p) === "engineering" ? "grid" : "book"} /></span><span className="sl-small">{t("Sample program", "نمونہ پروگرام")} <bdi>{String(i + 1).padStart(2, "0")}</bdi></span></div><h3 dir="auto">{p.name}</h3><p>{t("View the sample learning schedule and start an admissions conversation with the office.", "نمونہ تعلیمی شیڈول دیکھیں اور دفتر سے داخلہ کے بارے میں بات کریں۔")}</p><details><summary>{t("Explore this program", "پروگرام کی تفصیل")}<span>+</span></summary><p>{t("This is an illustrative class, not a confirmed offering. Course details, entry requirements and current places need office confirmation.", "یہ نمونہ کلاس ہے۔ کورس کی تفصیل، داخلہ شرائط اور دستیاب نشستیں دفتر سے تصدیق کریں۔")}</p><Link href={portal("admissions", `&enquire=1&program=${encodeURIComponent(p.id)}`)} className="sl-text-link">{t("Enquire about this program", "اس پروگرام کے بارے میں پوچھیں")}<Arrow /></Link></details></article>)}
          {!programsUnavailable && shown.length > 0 && <article className="sl-program sl-program-help"><SIcon name="chat" /><h3>{t("Still finding your path?", "ابھی اپنا راستہ تلاش کر رہے ہیں؟")}</h3><p>{t("Ask about classes, requirements or the next campus visit. The assistant can connect you to the office.", "کلاس، شرائط یا ملاقات کے بارے میں پوچھیں۔ اسسٹنٹ دفتر سے رابطہ کروا سکتا ہے۔")}</p><Link href={portal("messages")} className="sl-btn">{t("Talk to admissions", "داخلہ ٹیم سے بات کریں")}<Arrow /></Link></article>}
        </div>
        {(programsUnavailable || shown.length === 0) && <div className="sl-empty" role="status"><SIcon name="book" /><h3>{programsUnavailable ? t("Program directory is temporarily unavailable", "پروگرام کی فہرست فی الحال دستیاب نہیں") : programs.length ? t("No programs match your search", "تلاش کے مطابق پروگرام نہیں ملا") : t("No sample programs are listed yet", "ابھی نمونہ پروگرام درج نہیں")}</h3><p>{t("The office can help with current program information.", "دفتر موجودہ پروگرام کی معلومات دے سکتا ہے۔")}</p><Link className="sl-text-link" href={portal("messages")}>{t("Ask the office", "دفتر سے پوچھیں")}<Arrow /></Link></div>}
      </section>
      <section id="learning" className="sl-learning sl-section"><div className="sl-wrap sl-learning-grid"><figure className="sl-study"><img src="/school/study.webp" width="1024" height="683" loading="lazy" alt={t("Illustrative adult students reading in a fictional library", "فرضی لائبریری میں پڑھتے بالغ طلبہ کی نمائشی تصویر")} /><figcaption>{t("Illustrative learning environment, not actual premises", "نمونہ تعلیمی ماحول، حقیقی کیمپس کی تصویر نہیں")}</figcaption><span className="sl-study-stamp" aria-hidden="true"><SIcon name="cap" /></span></figure><div><p className="sl-eyebrow">{t("Make room for learning", "تعلیم کے لیے جگہ بنائیں")}</p><h2>{t("Less guesswork.", "واضح معلومات۔")}<br />{t("More connection.", "بہتر رابطہ۔")}</h2><p>{t("A school experience should be easy to follow. This website concept brings the first enquiry and everyday family updates together.", "تعلیمی معلومات آسانی سے سمجھ آنی چاہئیں۔ یہ ویب سائٹ نمونہ پہلی درخواست اور روزمرہ معلومات کو ایک جگہ لاتا ہے۔")}</p><div className="sl-learning-features">{[["book", "Know what comes next", "اگلا قدم جانیں", "Published homework and a recorded timetable in the parent demo.", "والدین ڈیمو میں شائع شدہ ہوم ورک اور شیڈول۔"], ["chat", "Keep the conversation open", "گفتگو جاری رکھیں", "A shared assistant conversation with school office support.", "اسکول دفتر کی مدد کے ساتھ مربوط گفتگو۔"], ["cap", "See the recorded progress", "ریکارڈ شدہ نتائج دیکھیں", "Published assessment reports with printable summaries.", "شائع شدہ امتحانی نتائج اور قابل پرنٹ رپورٹس۔"]].map(([icon, en, u, sub, subUr]) => <div key={en}><span className="sl-icon-tile"><SIcon name={icon} /></span><span><h3>{t(en, u)}</h3><p>{t(sub, subUr)}</p></span></div>)}</div></div></div></section>
      <section id="family" className="sl-section sl-wrap"><div className="sl-family"><div className="sl-family-copy"><p className="sl-eyebrow">{t("For the whole family", "پورے خاندان کے لیے")}</p><h2>{t("School days, ", "تعلیمی دن، ")}<br />{t("all in one place.", "ایک ہی جگہ۔")}</h2><p>{t("From class schedules to homework and fee records, explore the working parent portal with fictional data.", "کلاس شیڈول سے ہوم ورک اور فیس ریکارڈ تک، فرضی معلومات کے ساتھ والدین پورٹل دیکھیں۔")}</p><Link href={portal()} className="sl-btn sl-white">{t("Explore parent portal", "والدین پورٹل دیکھیں")}<Arrow /></Link><small>{t("Sample families only. Demo role switching is not a real student login.", "صرف نمونہ خاندان۔ ڈیمو کردار بدلنا حقیقی طالب علم لاگ ان نہیں۔")}</small></div><div className="sl-portal-preview" aria-label={t("Illustrative parent portal preview", "والدین پورٹل کا نمائشی نمونہ")}><div className="sl-preview-head"><span className="sl-avatar">{initials}</span><div><b>Campusflow</b><small>{t("Connected family demo", "مربوط خاندان کا ڈیمو")}</small></div><span className="sl-preview-chip">{t("Sample", "نمونہ")}</span></div><h3>{t("A little clarity, every day.", "ہر دن، واضح معلومات۔")}</h3><div className="sl-preview-grid">{[["check", "Attendance", "حاضری", "Recorded days", "ریکارڈ شدہ دن", "attendance"], ["book", "Homework", "ہوم ورک", "Published tasks", "شائع شدہ کام", "homework"], ["cap", "Results", "نتائج", "Published reports", "شائع شدہ رپورٹس", "results"], ["fee", "Fees", "فیس", "Sample ledger", "نمونہ رجسٹر", "fees"]].map(([icon, en, u, sub, subUr, tab]) => <Link key={en} href={portal(tab)}><SIcon name={icon} /><b>{t(en, u)}</b><small>{t(sub, subUr)}</small><Arrow /></Link>)}</div><Link href={portal("timetable")} className="sl-preview-time"><span className="sl-icon-tile"><SIcon name="clock" /></span><span><b>{t("Your class timetable", "آپ کی کلاس کا شیڈول")}</b><small>{t("Lessons, dates and class details", "اسباق، تاریخیں اور کلاس کی تفصیل")}</small></span><Arrow /></Link></div></div></section>
      <section id="admissions" className="sl-section sl-wrap"><div className="sl-section-head"><div><p className="sl-eyebrow">{t("A welcoming first step", "تعلیم کی طرف پہلا قدم")}</p><h2>{t("Your journey, ", "آپ کا سفر، ")}<br />{t("one step at a time.", "ایک وقت میں ایک قدم۔")}</h2></div><Link href={portal("admissions", "&enquire=1")} className="sl-btn">{t("Start an enquiry", "درخواست شروع کریں")}<Arrow /></Link></div><div className="sl-steps">{[["01", "Find your program", "پروگرام منتخب کریں", "Browse sample classes and ask the office to confirm what is available.", "نمونہ کلاسیں دیکھیں اور دفتر سے دستیابی معلوم کریں۔", "#programs", "Explore programs", "پروگرام دیکھیں"], ["02", "Tell us what you're looking for", "اپنی ضرورت بتائیں", "Send a fictional admissions enquiry in the connected portal. The office can review it.", "مربوط پورٹل میں فرضی داخلہ درخواست دیں۔ دفتر اس کا جائزہ لے سکتا ہے۔", portal("admissions", "&enquire=1"), "Start an enquiry", "درخواست شروع کریں"], ["03", "Plan a visit", "ملاقات طے کریں", "Choose a stored, available 30-minute campus visit slot. All times are Pakistan Standard Time.", "دستیاب ۳۰ منٹ کی ملاقات منتخب کریں۔ تمام اوقات پاکستانی وقت کے مطابق ہیں۔", portal("admissions", "&visit=1"), "Check visit times", "ملاقات کے اوقات دیکھیں"]].map(([n, en, u, sub, subUr, href, cta, ctaUr]) => <article key={n}><span className="sl-step-number">{n}</span><h3>{t(en, u)}</h3><p>{t(sub, subUr)}</p><Link href={href} className="sl-text-link">{t(cta, ctaUr)}<Arrow /></Link></article>)}</div><p className="sl-small">{t("Enquiries and visits are simulated. Admissions decisions, fees and entry requirements must be confirmed with the real institution.", "درخواستیں اور ملاقاتیں نمونہ ہیں۔ حقیقی داخلہ، فیس اور شرائط ادارے سے تصدیق کریں۔")}</p></section>
      <section className="sl-community sl-section"><div className="sl-wrap"><div className="sl-section-head"><div><p className="sl-eyebrow">{t("From the local community", "مقامی لوگوں کی رائے")}</p><h2>{t("A place in Quetta.", "کوئٹہ میں ایک ادارہ۔")}<br />{t("A voice in the community.", "مقامی لوگوں کی آواز۔")}</h2></div><div className="sl-review-total">{f.rating != null && <strong><bdi>{f.rating}</bdi><span>/ 5</span></strong>}<p>{f.reviews != null ? <bdi>{f.reviews.toLocaleString("en-US")} {t("Google reviews", "گوگل ریویوز")}</bdi> : t("Explore the Google listing", "گوگل پروفائل دیکھیں")}</p><Link className="sl-text-link" href={maps} external>{t("View Google profile", "گوگل پروفائل دیکھیں")} ↗</Link></div></div><div className="sl-review-grid">{praise.map((p, i) => <article key={i}><span className="sl-quote" aria-hidden="true">“</span><p className="sl-review-quote" dir="auto">{p.quotes[0]}</p><b>{t("From the Google listing", "گوگل پروفائل سے")}</b><small>{t("Excerpt from researched Google reviews", "جائزہ لیے گئے گوگل ریویوز سے اقتباس")}</small></article>)}</div>{!praise.length && <p className="sl-small">{t("No researched review excerpts are available. Visit the Google profile for current feedback.", "ریویوز کے اقتباسات موجود نہیں۔ تازہ رائے کے لیے گوگل پروفائل دیکھیں۔")}</p>}</div></section>
      <section id="visit" className="sl-section sl-wrap"><div className="sl-section-head"><div><p className="sl-eyebrow">{t("Let's meet", "آئیں، ملاقات کریں")}</p><h2>{t("Find your way here.", "یہاں آنے کا راستہ۔")}</h2></div><p>{t("Check the listed hours, get directions, or plan a sample visit with the office.", "درج شدہ اوقات دیکھیں، راستہ معلوم کریں یا دفتر کی نمونہ ملاقات طے کریں۔")}</p></div><div className="sl-visit-grid"><div className="sl-map"><svg viewBox="0 0 620 430" aria-hidden="true"><rect width="620" height="430" fill="currentColor"/><g stroke="var(--sl-map-road)" strokeWidth="28" fill="none"><path d="M-40 100h300l170 150h230M-20 370l210-190L330-30M490-30v240l-170 220M0 225h650"/></g><g fill="var(--sl-map-block)"><rect x="25" y="22" width="133" height="58" rx="12"/><rect x="352" y="20" width="100" height="152" rx="12"/><rect x="35" y="260" width="107" height="66" rx="12"/><rect x="475" y="286" width="114" height="107" rx="12"/></g><circle cx="320" cy="213" r="57" fill="var(--sl-blue)" opacity=".09"/><circle cx="320" cy="213" r="34" fill="var(--sl-blue)"/><path d="m301 209 19-10 19 10-19 10Zm6 7v10q13 8 26 0v-10" fill="none" stroke="white" strokeWidth="2.5"/></svg><span className="sl-map-tag"><b dir="auto">{b.name}</b><small>{t("Schematic illustration, not a navigational map", "نمونہ خاکہ، حقیقی نقشہ نہیں")}</small></span><Link href={maps} external className="sl-btn">{t("Open Google Maps", "گوگل میپس کھولیں")} ↗</Link></div><div className="sl-location"><h3>{t("Campus information", "کیمپس کی معلومات")}</h3><p dir="auto">{f.address || t("Address not recorded. Ask the office.", "پتا درج نہیں۔ دفتر سے پوچھیں۔")}</p><div className="sl-hours"><b>{t("Listed visiting hours", "درج شدہ اوقات")}</b><small>{t("Pakistan Standard Time · Confirm before travelling", "پاکستانی وقت، آنے سے پہلے تصدیق کریں")}</small>{f.hours.length ? f.hours.map((h, i) => <div key={i}><span>{ur ? ({Monday:"پیر",Tuesday:"منگل",Wednesday:"بدھ",Thursday:"جمعرات",Friday:"جمعہ",Saturday:"ہفتہ",Sunday:"اتوار"}[h.day] ?? h.day) : h.day}</span><bdi>{h.hours}</bdi></div>) : <p>{t("Hours not recorded. Contact the office.", "اوقات درج نہیں۔ دفتر سے پوچھیں۔")}</p>}</div><Link className="sl-text-link" href={portal("admissions", "&visit=1")}>{t("Choose a sample visit time", "نمونہ ملاقات کا وقت منتخب کریں")}<Arrow /></Link></div></div></section>
      <section className="sl-section sl-wrap sl-faq"><div><p className="sl-eyebrow">{t("Good questions, clear answers", "اچھے سوالات، واضح جواب")}</p><h2>{t("A few things", "چند ضروری")}<br />{t("to know.", "معلومات۔")}</h2><Link href={portal("messages")} className="sl-text-link">{t("Ask another question", "مزید سوال پوچھیں")}<Arrow /></Link></div><div>{[["Are these the actual programs offered?", "کیا یہ حقیقی پروگرام ہیں؟", "Programs on this page are fictional classes from the outreach demo. Ask the office to confirm the current courses, entry requirements and available places.", "اس صفحے پر پروگرام آؤٹ ریچ ڈیمو کی فرضی کلاسیں ہیں۔ حقیقی کورس، شرائط اور نشستیں دفتر سے معلوم کریں۔"], ["How do I check fees and admission dates?", "فیس اور داخلہ تاریخ کیسے معلوم کریں؟", "Use the admissions conversation to ask the office. The parent demo contains synthetic fee records, not an approved fee schedule or real payments.", "داخلہ گفتگو میں دفتر سے پوچھیں۔ والدین ڈیمو میں فرضی فیس ریکارڈ ہے، حقیقی فیس شیڈول یا ادائیگی نہیں۔"], ["Can I book a campus visit?", "کیا کیمپس ملاقات بک کر سکتے ہیں؟", "Yes, in the demo. Open the visit planner and choose an available 30-minute slot within the next 14 days and preview expiry. Confirmation happens only after the slot is successfully reserved. No real visit is booked.", "ڈیمو میں ہاں۔ اگلے ۱۴ دن اور ڈیمو کی مدت کے اندر دستیاب ۳۰ منٹ کا وقت منتخب کریں۔ وقت محفوظ ہونے کے بعد ہی تصدیق ہوتی ہے۔ حقیقی ملاقات بک نہیں ہوتی۔"], ["What can families see in the parent portal?", "والدین پورٹل میں کیا دیکھ سکتے ہیں؟", "Explore recorded attendance, timetable, published homework and results, sample fees, leave requests and messages for a fictional family. Unpublished academic drafts are not shown to parents.", "فرضی خاندان کی حاضری، شیڈول، شائع شدہ ہوم ورک اور نتائج، نمونہ فیس، چھٹی درخواست اور پیغامات دیکھیں۔ غیر شائع شدہ تعلیمی مسودے والدین کو نہیں دکھتے۔"]].map(([en, u, answer, answerUr]) => <details key={en}><summary>{t(en, u)}<span>+</span></summary><p>{t(answer, answerUr)}</p></details>)}</div></section>
      <section className="sl-wrap sl-closing"><div><p className="sl-eyebrow">{t("The first step is a conversation", "پہلا قدم ایک گفتگو ہے")}</p><h2>{t("Ready for your", "اپنے اگلے قدم")}<br />{t("next chapter?", "کے لیے تیار ہیں؟")}</h2><div className="sl-actions"><Link href={portal("admissions", "&enquire=1")} className="sl-btn">{t("Start an admissions enquiry", "داخلہ درخواست شروع کریں")}<Arrow /></Link><Link href={portal("admissions", "&visit=1")} className="sl-btn sl-outline">{t("Plan a campus visit", "کیمپس ملاقات طے کریں")}</Link></div></div><span aria-hidden="true" className="sl-closing-art"><SIcon name="cap" /></span></section>
    </main>
    <footer className="sl-wrap sl-footer"><div className="sl-footer-top"><div><b dir="auto">{b.name}</b><p>{kind} · {t("Quetta", "کوئٹہ")}</p></div><nav aria-label={t("Footer navigation", "فوٹر نیویگیشن")}><Link href="#programs">{t("Programs", "پروگرام")}</Link><Link href={portal()}>{t("Parent portal", "والدین پورٹل")}</Link><Link href={base + query}>{t("Back to review report", "جائزہ رپورٹ پر واپس")}</Link></nav></div><p>{t("Landing page concept by NexusPoint. Programs, portal records and learning imagery are illustrative. No real applications, visits, payments or notifications are sent.", "نیکسس پوائنٹ کا لینڈنگ پیج نمونہ۔ پروگرام، پورٹل ریکارڈ اور تصاویر نمائشی ہیں۔ حقیقی درخواست، ملاقات، ادائیگی یا اطلاع نہیں ہوتی۔")}</p></footer>
  </div>;
}
