#!/usr/bin/env python3
"""
Catalog builder for free-for-dev-scout.
Fetches the free-for-dev README (github.com/ripienaar/free-for-dev), parses its per-category
bullet lists, and writes catalog/free-for-dev.md in free-for-dev-scout's scannable entry format.

Usage:
    python .claude/skills/free-for-dev-scout/scripts/fetch_free_for_dev.py
    python .claude/skills/free-for-dev-scout/scripts/fetch_free_for_dev.py --output /path/to/catalog.md
    python .claude/skills/free-for-dev-scout/scripts/fetch_free_for_dev.py --source /path/to/local/README.md
"""
from __future__ import annotations

import argparse
import re
import sys
import urllib.request
from datetime import date
from pathlib import Path

README_URL = "https://raw.githubusercontent.com/ripienaar/free-for-dev/master/README.md"

# Matches a bullet entry like: * [Name](url) - Description   (any indent depth)
ROW_RE = re.compile(r"^\s*\*\s*\[([^\]]+)\]\(([^)]+)\)\s*(?:-\s*(.*))?$")
CATEGORY_RE = re.compile(r"^## (.+)$")


def fetch_readme(source: str | None) -> str:
    if source:
        return Path(source).read_text(encoding="utf-8")
    with urllib.request.urlopen(README_URL, timeout=30) as resp:
        return resp.read().decode("utf-8")


def parse_catalog(readme: str) -> dict[str, list[dict]]:
    """Parse ## category sections into free-tier service entries.

    free-for-dev nests some entries under a plain bullet (e.g. individual AWS/GCP
    services listed under the parent cloud provider) — those without their own
    [name](url) link are skipped rather than merged into the parent's description,
    to keep entries scannable. Long descriptions that wrap onto an indented
    continuation line (no leading '*') are rejoined onto the entry that owns them.
    """
    catalog: dict[str, list[dict]] = {}
    current_category: str | None = None
    current_entry: dict | None = None

    for line in readme.splitlines():
        cat_match = CATEGORY_RE.match(line)
        if cat_match:
            current_category = cat_match.group(1).strip()
            catalog.setdefault(current_category, [])
            current_entry = None
            continue
        if current_category is None:
            continue

        row = ROW_RE.match(line)
        if row:
            name, url, desc = row.group(1).strip(), row.group(2).strip(), (row.group(3) or "").strip()
            current_entry = {"name": name, "url": url, "description": desc}
            catalog[current_category].append(current_entry)
            continue

        stripped = line.strip()
        if not stripped or stripped.startswith("**[") or stripped.startswith("#"):
            current_entry = None
            continue
        if stripped.startswith("*"):
            # A nested bullet with no [name](url) of its own (e.g. individual AWS/GCP
            # services listed under the parent cloud provider) — not its own catalog
            # entry, and not part of the parent's description either.
            current_entry = None
            continue
        # A non-bulleted, non-empty line right after an entry is a wrapped continuation
        # of that entry's description (free-for-dev wraps some long descriptions).
        if current_entry is not None:
            current_entry["description"] = (current_entry["description"] + " " + stripped).strip()

    return {k: v for k, v in catalog.items() if v}


def format_catalog(catalog: dict[str, list[dict]]) -> str:
    total = sum(len(v) for v in catalog.values())
    lines = [
        "# Free-for-Dev Catalog",
        f"*Last updated: {date.today().isoformat()} — {total} services across {len(catalog)} categories*",
        "*Auto-generated by free-for-dev-scout from github.com/ripienaar/free-for-dev*",
        "",
    ]
    for category, services in catalog.items():
        lines += [f"## {category}", ""]
        for s in services:
            lines.append(f"### {s['name']}")
            lines.append(f"- **URL:** {s['url']}")
            lines.append(f"- **Category:** {category}")
            if s["description"]:
                lines.append(f"- **Free tier:** {s['description']}")
            lines.append("")
    return "\n".join(lines)


def main() -> None:
    p = argparse.ArgumentParser(description="Build the free-for-dev-scout catalog from ripienaar/free-for-dev.")
    p.add_argument("--output", default=None, help="Output path for catalog.md")
    p.add_argument("--source", default=None, help="Local README.md path instead of fetching from GitHub")
    args = p.parse_args()

    skill_dir = Path(__file__).resolve().parent.parent
    out_path = Path(args.output) if args.output else skill_dir / "catalog" / "free-for-dev.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    print("Fetching free-for-dev README..." if not args.source else f"Reading {args.source}...", flush=True)
    readme = fetch_readme(args.source)

    catalog = parse_catalog(readme)
    if not catalog:
        print("Warning: no categories parsed — check the README format hasn't changed.", file=sys.stderr)
        sys.exit(1)

    out_path.write_text(format_catalog(catalog), encoding="utf-8")
    total = sum(len(v) for v in catalog.values())
    print(f"Done — {total} services across {len(catalog)} categories written to {out_path}")


if __name__ == "__main__":
    main()
