"""Keep .agents/skills/ as pointers to the canonical skills in .claude/skills/.

Every SKILL.md under .claude/skills/ (tracked, or untracked but not gitignored) gets a pointer at
the same relative path under .agents/skills/: the canonical frontmatter copied verbatim, so tools
that index .agents/skills/ still see the right name and description, plus a body that sends the
reader to the canonical file. A pointer carries no instructions of its own, so its content cannot
drift. Frontmatter and coverage still can, and --check reports both.

This replaced a full-copy mirror on 2026-09-13. Within five days that copy had 17+ edited files
never re-copied, and its original creation had run a blind claude-to-Codex replace that pointed
46 files at a `.Codex/skills/` path that does not exist.

Three things are never touched, each learned the hard way during that first conversion:
- Gitignored content. Nested `.gitignore` files are always kept: deleting seven of them un-ignored
  140 copied files, real prospect voice files and whole-site SEO crawls among them, in a public repo.
- Skills linked between the two trees. The skills installer makes some `.claude/skills/<name>` a
  directory junction into `.agents/skills/<name>`, so both paths are the same files. Treating
  remotion-best-practices as mirrorable wrote the pointer into its canonical SKILL.md and deleted
  its rule files. Any skill whose canonical and mirror paths resolve to the same place is skipped.
- Orphans. Mirror folders with no canonical skill are reported, never deleted.
`agents/openai.yaml` (Codex UI metadata) is kept too.

Usage:
  python scripts/sync_agents_mirror.py           # write pointers, delete stale mirror files
  python scripts/sync_agents_mirror.py --check   # report drift, exit 1 if any, change nothing
"""
import argparse
import os
import shutil
import stat
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
CANON = ".claude/skills"
MIRROR = ".agents/skills"
KEEP_SUFFIXES = ("/agents/openai.yaml", "/.gitignore")
CACHE_DIRS = ("__pycache__", ".impeccable")  # gitignored, but they keep emptied folders alive


def git_files(prefix):
    """Files under prefix that exist on disk and are tracked or untracked-but-not-ignored.

    The on-disk filter matters: a tracked file deleted but not yet committed is still listed by
    git, and counting it would report phantom drift after every run until the commit."""
    out = subprocess.run(
        ["git", "ls-files", "-z", "--cached", "--others", "--exclude-standard", "--", prefix],
        cwd=REPO, capture_output=True, check=True,
    ).stdout.decode("utf-8")
    return sorted({f for f in out.split("\0") if f and (REPO / f).is_file()})


def top(path):
    return path.split("/")[2]


def is_link(path):
    return path.is_symlink() or path.is_junction()


def inside(path, root):
    return os.path.realpath(path).startswith(os.path.realpath(root) + os.sep)


def frontmatter(text, rel_dir):
    lines = text.splitlines()
    if lines and lines[0].strip() == "---":
        for i, line in enumerate(lines[1:], start=1):
            if line.strip() == "---":
                return "\n".join(lines[1:i])
    return f"name: {rel_dir.rsplit('/', 1)[-1]}\ndescription: Pointer to {CANON}/{rel_dir}/SKILL.md."


def pointer(rel_dir, fm):
    return (
        f"---\n{fm}\n---\n\n"
        f"# Pointer to `{CANON}/{rel_dir}/`\n\n"
        f"This file is a pointer, not a copy. Read and follow the canonical skill at\n"
        f"`{CANON}/{rel_dir}/SKILL.md` (path from the repository root), and resolve every file it\n"
        f"references relative to that canonical folder, not this one.\n\n"
        f"Generated by `scripts/sync_agents_mirror.py`. Edit the canonical skill, never this file.\n"
    )


def main():
    ap = argparse.ArgumentParser(description="Regenerate the .agents/skills/ pointer files.")
    ap.add_argument("--check", action="store_true", help="report drift, exit 1 if any, change nothing")
    args = ap.parse_args()

    expected, linked = {}, set()
    for f in git_files(CANON):
        rel_dir = f[len(CANON) + 1:-len("/SKILL.md")] if f.endswith("/SKILL.md") else ""
        if not rel_dir:
            continue
        name, p = top(f), f"{MIRROR}/{rel_dir}/SKILL.md"
        if (is_link(REPO / CANON / name) or is_link(REPO / MIRROR / name)
                or not inside(REPO / f, REPO / CANON)
                or os.path.realpath(REPO / f) == os.path.realpath(REPO / p)):
            linked.add(name)
            continue
        text = (REPO / f).read_bytes().decode("utf-8")
        expected[p] = pointer(rel_dir, frontmatter(text, rel_dir))
    expected = {p: body for p, body in expected.items() if top(p) not in linked}
    managed = {top(p) for p in expected}

    mirror = [f for f in git_files(MIRROR) if top(f) not in linked and inside(REPO / f, REPO / MIRROR)]
    stale = [f for f in mirror if top(f) in managed and f not in expected and not f.endswith(KEEP_SUFFIXES)]
    orphans = sorted({top(f) for f in mirror if top(f) not in managed})
    outdated = [p for p, body in expected.items()
                if not (REPO / p).is_file() or (REPO / p).read_bytes().decode("utf-8") != body]

    print(f"canonical skills: {len(expected)} | pointers to write: {len(outdated)} | "
          f"stale mirror files: {len(stale)} | orphan folders: {len(orphans)} | linked, left alone: {len(linked)}")
    for name in sorted(linked):
        print(f"  linked between the trees, left alone: {name}")
    for name in orphans:
        print(f"  orphan (no canonical skill, not deleted): {MIRROR}/{name}/")
    if args.check:
        for p in outdated[:15]:
            print(f"  outdated or missing: {p}")
        for p in stale[:15]:
            print(f"  stale: {p}")
        return 1 if outdated or stale or orphans else 0

    for p in outdated:
        (REPO / p).parent.mkdir(parents=True, exist_ok=True)
        (REPO / p).write_bytes(expected[p].encode("utf-8"))
    for p in stale:
        (REPO / p).unlink()
    for name in managed:
        root = REPO / MIRROR / name
        for cache in [d for c in CACHE_DIRS for d in root.rglob(c) if d.is_dir()]:
            shutil.rmtree(cache, ignore_errors=True)
        for d in sorted((d for d in root.rglob("*") if d.is_dir()), key=lambda d: len(d.parts), reverse=True):
            if not any(d.iterdir()):
                try:
                    os.chmod(d, stat.S_IWRITE)  # some folders carry the Windows read-only attribute
                    d.rmdir()
                except OSError:
                    pass  # an empty folder is invisible to git, not worth failing the run over
    return 0


if __name__ == "__main__":
    sys.exit(main())
