#!/usr/bin/env python3
"""
Catalog builder for free-tool-scout.
Runs 14 Exa searches across 7 categories, deduplicates by URL, and writes catalog/tools.md.

Usage:
    python .claude/skills/free-tool-scout/scripts/fetch_tools.py
    python .claude/skills/free-tool-scout/scripts/fetch_tools.py --output /path/to/catalog.md
"""
from __future__ import annotations

import sys
import argparse
from datetime import date
from pathlib import Path

# Repo root is 5 levels up from this file:
# fetch_tools.py -> scripts/ -> free-tool-scout/ -> skills/ -> .claude/ -> Nexis/
REPO_ROOT = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(REPO_ROOT))

from tools.exa.exa_client import search  # noqa: E402

CATEGORIES: dict[str, list[str]] = {
    "Marketing": [
        "best free email marketing tools 2025 free plan",
        "free social media scheduling SEO analytics tools small business",
    ],
    "Business Operations": [
        "best free CRM tools small business 2025",
        "free project management tools for teams 2025",
    ],
    "Market Research": [
        "free market research competitor analysis tools 2025",
        "free survey audience research tools small business",
    ],
    "Productivity": [
        "best free productivity note-taking tools 2025",
        "free workflow automation no-code tools",
    ],
    "Content Creation": [
        "best free content creation video editing tools 2025",
        "free AI writing design tools creators",
    ],
    "AI Tools": [
        "best free AI tools business productivity 2025",
        "free AI code generation image generation tools",
    ],
    "Finance Management": [
        "best free accounting invoicing tools small business 2025",
        "free expense tracking budgeting tools",
    ],
}


def fetch_category(category: str, queries: list[str]) -> list[dict]:
    seen_urls: set[str] = set()
    results = []
    for query in queries:
        try:
            data = search(
                query,
                num_results=8,
                type="neural",
                text=False,
                highlights=True,
                summary=False,
            )
            for r in data.get("results", []):
                url = r.get("url", "").lower().split("#")[0].rstrip("/")
                if not url or url in seen_urls:
                    continue
                seen_urls.add(url)
                results.append({
                    "title": r.get("title") or "Unknown",
                    "url": r.get("url", ""),
                    "highlights": r.get("highlights") or [],
                    "category": category,
                })
        except Exception as e:
            print(f"  Warning: search failed for '{query}': {e}", file=sys.stderr)
    return results


def format_catalog(catalog: dict[str, list[dict]]) -> str:
    total = sum(len(v) for v in catalog.values())
    lines = [
        "# Free Tool Catalog",
        f"*Last updated: {date.today().isoformat()} — {total} tools across {len(catalog)} categories*",
        "*Auto-generated by free-tool-scout via Exa AI*",
        "",
    ]
    for category, tools in catalog.items():
        lines += [f"## {category}", ""]
        for t in tools:
            snippet = " ".join(t["highlights"][:2]).strip() if t["highlights"] else ""
            lines.append(f"### {t['title']}")
            lines.append(f"- **URL:** {t['url']}")
            lines.append(f"- **Category:** {category}")
            if snippet:
                lines.append(f"- **About:** {snippet[:280]}")
            lines.append("- **Free tier:** (verify at URL)")
            lines.append("")
    return "\n".join(lines)


def main() -> None:
    p = argparse.ArgumentParser(description="Build the free-tool-scout catalog via Exa AI.")
    p.add_argument("--output", default=None, help="Output path for catalog.md")
    args = p.parse_args()

    skill_dir = Path(__file__).resolve().parent.parent
    out_path = Path(args.output) if args.output else skill_dir / "catalog" / "tools.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    catalog: dict[str, list[dict]] = {}
    for category, queries in CATEGORIES.items():
        print(f"Searching: {category}...", flush=True)
        results = fetch_category(category, queries)
        catalog[category] = results
        print(f"  -> {len(results)} tools")

    out_path.write_text(format_catalog(catalog), encoding="utf-8")
    total = sum(len(v) for v in catalog.values())
    print(f"\nDone — {total} tools written to {out_path}")


if __name__ == "__main__":
    main()
