#!/usr/bin/env python3
"""
Catalog builder for selfhosted-scout.
Fetches the awesome-selfhosted README (github.com/awesome-selfhosted/awesome-selfhosted), parses
its per-category entries, and writes catalog/selfhosted.md in selfhosted-scout's scannable format.

Usage:
    python .claude/skills/selfhosted-scout/scripts/fetch_selfhosted.py
    python .claude/skills/selfhosted-scout/scripts/fetch_selfhosted.py --output /path/to/catalog.md
    python .claude/skills/selfhosted-scout/scripts/fetch_selfhosted.py --source /path/to/local/README.md
"""
from __future__ import annotations

import argparse
import re
import sys
import urllib.request
from datetime import date
from pathlib import Path

README_URL = "https://raw.githubusercontent.com/awesome-selfhosted/awesome-selfhosted/master/README.md"

# Matches an entry like: - [Name](url) `⚠` - Description. (...) `License` `Language/Platform`
ROW_RE = re.compile(r"^- \[([^\]]+)\]\(([^)]+)\)\s*(.*)$")
TAG_RE = re.compile(r"`([^`]+)`")
CATEGORY_RE = re.compile(r"^### (.+)$")
SECTION_START = "## Software"
SECTION_END = "## List of Licenses"


def fetch_readme(source: str | None) -> str:
    if source:
        return Path(source).read_text(encoding="utf-8")
    with urllib.request.urlopen(README_URL, timeout=30) as resp:
        return resp.read().decode("utf-8")


def parse_row(line: str, category: str) -> dict | None:
    m = ROW_RE.match(line.strip())
    if not m:
        return None
    name, url, rest = m.group(1).strip(), m.group(2).strip(), m.group(3)

    tags = TAG_RE.findall(rest)
    unmaintained = "⚠" in tags
    real_tags = [t for t in tags if t != "⚠"]
    license_ = real_tags[0] if len(real_tags) > 0 else "Unknown"
    platform = real_tags[1] if len(real_tags) > 1 else "Unknown"

    description = TAG_RE.sub("", rest).strip()
    description = re.sub(r"^-\s*", "", description).strip()

    return {
        "name": name,
        "url": url,
        "category": category,
        "description": description,
        "license": license_,
        "platform": platform,
        "unmaintained": unmaintained,
    }


def parse_catalog(readme: str) -> dict[str, list[dict]]:
    """Parse ### category sections between ## Software and ## List of Licenses."""
    catalog: dict[str, list[dict]] = {}
    current_category: str | None = None
    in_software_section = False

    for line in readme.splitlines():
        if line.strip() == SECTION_START:
            in_software_section = True
            continue
        if line.strip() == SECTION_END:
            break
        if not in_software_section:
            continue

        cat_match = CATEGORY_RE.match(line.strip())
        if cat_match:
            current_category = cat_match.group(1).strip()
            catalog.setdefault(current_category, [])
            continue
        if current_category is None:
            continue

        entry = parse_row(line, current_category)
        if entry:
            catalog[current_category].append(entry)

    return {k: v for k, v in catalog.items() if v}


def format_catalog(catalog: dict[str, list[dict]]) -> str:
    total = sum(len(v) for v in catalog.values())
    lines = [
        "# Self-Hosted Software Catalog",
        f"*Last updated: {date.today().isoformat()} — {total} projects across {len(catalog)} categories*",
        "*Auto-generated by selfhosted-scout from github.com/awesome-selfhosted/awesome-selfhosted*",
        "",
    ]
    for category, projects in catalog.items():
        lines += [f"## {category}", ""]
        for p in projects:
            flag = " (unmaintained)" if p["unmaintained"] else ""
            lines.append(f"### {p['name']}{flag}")
            lines.append(f"- **URL:** {p['url']}")
            lines.append(f"- **Category:** {category}")
            lines.append(f"- **License:** {p['license']}")
            lines.append(f"- **Platform/Language:** {p['platform']}")
            if p["description"]:
                lines.append(f"- **About:** {p['description']}")
            lines.append("")
    return "\n".join(lines)


def main() -> None:
    p = argparse.ArgumentParser(description="Build the selfhosted-scout catalog from awesome-selfhosted/awesome-selfhosted.")
    p.add_argument("--output", default=None, help="Output path for catalog.md")
    p.add_argument("--source", default=None, help="Local README.md path instead of fetching from GitHub")
    args = p.parse_args()

    skill_dir = Path(__file__).resolve().parent.parent
    out_path = Path(args.output) if args.output else skill_dir / "catalog" / "selfhosted.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    print("Fetching awesome-selfhosted README..." if not args.source else f"Reading {args.source}...", flush=True)
    readme = fetch_readme(args.source)

    catalog = parse_catalog(readme)
    if not catalog:
        print("Warning: no categories parsed — check the README format hasn't changed.", file=sys.stderr)
        sys.exit(1)

    out_path.write_text(format_catalog(catalog), encoding="utf-8")
    total = sum(len(v) for v in catalog.values())
    print(f"Done — {total} projects across {len(catalog)} categories written to {out_path}")


if __name__ == "__main__":
    main()
